Support explicitly specified nested canonical links using :: syntax
osrf/sdformat pull request #355
Opened 2020-09-03 19:22 UTC by scpeters

Support for implicit nested canonical links (i.e. when `//model/@canonical_link` is empty) was added in #341, but explicitly specifying a nested link using `::` syntax (like `<model name="M" canonical_link="nested_model::nested_link">`) was not supported. This adds support for `::` syntax in the `Model::*ByName` and `Model::*NameExists` functions, which is enough to support explicit specification of nested canonical links using `::` syntax.

I split the `test/sdf/nested_invalid_explicit_canonical_link.sdf` test file into two parts, since it was demonstrating two different types of failures:

* test/sdf/nested_explicit_canonical_link.sdf: now a valid file in 1.8
* test/sdf/nested_without_links_invalid.sdf: still not supported

In this implementation, if `::` is detected in the name passed to `Model::*ByName` and `Model::*NameExists`, those functions will interpret all instances of `::` as separators between nested models and attempt to find a hierarchy of nested models that precedes the last instance of `::`. If such a nested model cannot be found, it checks for an object that matches the full name (including instances of `::`). I expect this behavior to be changed before we finish libsdformat11, but it is needed for now since included models are flattened by `addNestedModel` during parsing (see #284), so that some link, joint, and frame names may contain `::`. I left some comments in `Model::*ByName` about how to change this behavior when `::` become reserved and not allowed in frame names.

2020-09-10 00:46 UTC, azeey requested changes
> Reviewed 7 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[src/Model.cc, line 719 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGpOgXB42F54tfaWTji:-MGpOgXB42F54tfaWTjj:bguatxv) ([raw file](https://github.com/osrf/sdformat/blob/8b92f41f96ed6f2e2c164a785b902ab0283f262e/src/Model.cc#L719)):*
> ```cpp
>   }
> 
>   if (nullptr != nextModel && index != std::string::npos)
> ```

How do we want to handle old SDFormat files that may have `::` in a model name? For example

if `test.sdf`
```xml
<?xml version="1.0"?>
<sdf version='1.7'>
  <model name='MP'>
    <include>
      <uri>child_model</uri>
    </include>
  </model>
</sdf>
```

and `child_model/model.sdf` is 

```xml
<?xml version="1.0"?>
<sdf version='1.7'>
  <model name='M1'>
    <link name="L1"/>
    <model name='M2'>
      <link name="L2"/>
    </model>
  </model>
</sdf>
```

The result of `ign sdf -p test.sdf` is

```xml
<sdf version='1.7'>
  <model name='MP'>
    <frame name='M1::__model__' attached_to='M1::L1'>
      <pose relative_to='__model__'>0 0 0 0 -0 0</pose>
    </frame>
    <link name='M1::L1'>
      <pose relative_to='M1::__model__'>0 0 0 0 -0 0</pose>
    </link>
    <model name='M1::M2'> <!-- This is actually be M2 in the output. I think it's a bug -->
      <link name='L2'/>
    </model>
  </model>
</sdf>
```
 Querying for `MP::M1::M2::L2` will return nullptr.


<!-- Sent from Reviewable.io -->

2020-09-10 08:08 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @azeey and @EricCousineau-TRI)

___
*[src/Model.cc, line 719 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGpOgXB42F54tfaWTji:-MGr-3ux-IvdK2h-rsWq:b4h7z68) ([raw file](https://github.com/osrf/sdformat/blob/8b92f41f96ed6f2e2c164a785b902ab0283f262e/src/Model.cc#L719)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

How do we want to handle old SDFormat files that may have `::` in a model name? For example

if `test.sdf`
```xml
<?xml version="1.0"?>
<sdf version='1.7'>
  <model name='MP'>
    <include>
      <uri>child_model</uri>
    </include>
  </model>
</sdf>
```

and `child_model/model.sdf` is 

```xml
<?xml version="1.0"?>
<sdf version='1.7'>
  <model name='M1'>
    <link name="L1"/>
    <model name='M2'>
      <link name="L2"/>
    </model>
  </model>
</sdf>
```

The result of `ign sdf -p test.sdf` is

```xml
<sdf version='1.7'>
  <model name='MP'>
    <frame name='M1::__model__' attached_to='M1::L1'>
      <pose relative_to='__model__'>0 0 0 0 -0 0</pose>
    </frame>
    <link name='M1::L1'>
      <pose relative_to='M1::__model__'>0 0 0 0 -0 0</pose>
    </link>
    <model name='M1::M2'> <!-- This is actually be M2 in the output. I think it's a bug -->
      <link name='L2'/>
    </model>
  </model>
</sdf>
```
 Querying for `MP::M1::M2::L2` will return nullptr.
</blockquote></details>

You're right that this code will fail in that case, but I'm unsure how much to change it since I think this code is transitional (i.e. the [composition proposal](http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&#1-3-1-reserved-delimiter-token) reserves `::` so they won't be allowed in element names, which I expect will be implemented once we resolve #293 and #284). I do think this is a valuable test case, but I'm not sure if we should actually try to make it work in this branch or just add it as a disabled test that can be enabled when resolving #284 / #293.

Does that make sense?


<!-- Sent from Reviewable.io -->

2020-09-10 15:43 UTC, azeey requested changes
> Reviewed 2 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @scpeters)

___
*[src/Model.cc, line 719 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGpOgXB42F54tfaWTji:-MGse8XW4CEZXE_Da_xX:b-ks307m) ([raw file](https://github.com/osrf/sdformat/blob/6659e833edb965eabc03d86785bd9c69cdf5637a/src/Model.cc#L719)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

You're right that this code will fail in that case, but I'm unsure how much to change it since I think this code is transitional (i.e. the [composition proposal](http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&#1-3-1-reserved-delimiter-token) reserves `::` so they won't be allowed in element names, which I expect will be implemented once we resolve #293 and #284). I do think this is a valuable test case, but I'm not sure if we should actually try to make it work in this branch or just add it as a disabled test that can be enabled when resolving #284 / #293.

Does that make sense?
</blockquote></details>

`::` is reserved in SDFormat 1.8, but not in 1.7, so I don't think this will be an uncommon case. One thought is to remove the `::` during up-conversion and recreate the original nesting hierarchy based on the names, but I'm not sure how tractable that is.
___
*[test/integration/model_dom.cc, line 291 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGsdR4t3Q2ykgpRBGmM:-MGsdR4t3Q2ykgpRBGmN:b2khbz7) ([raw file](https://github.com/osrf/sdformat/blob/6659e833edb965eabc03d86785bd9c69cdf5637a/test/integration/model_dom.cc#L291)):*
> ```cpp
>   const std::string innerLinkNestedName = innerModelNestedName + "::inner_link";
>   EXPECT_TRUE(outerModel->LinkNameExists(innerLinkNestedName));
>   EXPECT_NE(nullptr, outerModel->LinkByName(innerLinkNestedName));
> ```

FYI, you could compare this against `innerModel->LinkByIndex(0)` to be more precise.


<!-- Sent from Reviewable.io -->

2020-09-10 16:53 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 3 unresolved discussions (waiting on @scpeters)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/355#-MGsvMMaBTsZQE7lLGQS:-MGsvMMaBTsZQE7lLGQT:b-joi8xw) (no related file):*
I guess I'm confused - why are you implementing this before #293 lands?

It seems like you'd need scaffolding that would go away once we have it, and there are also conversion issues that need to be solved as part of #293.

In #278, the way we formatted the dates (both #293 and #342), it seems like it could happen in parallel, but seeing y'all's discussion below, perhaps we'd want to wait?

---
*[a discussion](https://reviewable.io/reviews/osrf/sdformat/355#-MGsvm4x7H8nC8QRR4u2:-MGsvm4x7H8nC8QRR4u3:bx7brfc) (no related file):*
In the overview, can you state (above the text explanation) that this is gearing towards #342?

---


<!-- Sent from Reviewable.io -->

2020-09-10 19:05 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey and @scpeters)

___
*[src/Model.cc, line 719 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGpOgXB42F54tfaWTji:-MGtOzbG6yRgZ6BYSh58:b45x1bw) ([raw file](https://github.com/osrf/sdformat/blob/6659e833edb965eabc03d86785bd9c69cdf5637a/src/Model.cc#L719)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

`::` is reserved in SDFormat 1.8, but not in 1.7, so I don't think this will be an uncommon case. One thought is to remove the `::` during up-conversion and recreate the original nesting hierarchy based on the names, but I'm not sure how tractable that is.
</blockquote></details>

Per f2f, it should be OK to be temporarily backwards-incompatible in code, given that:

- We ensure that "master" is clearly denoted as unstable in the README
- The breakage is shown in a unittest with a clear comment.
- There's a TODO to resolve the comment afterwards.


<!-- Sent from Reviewable.io -->

2020-09-10 19:06 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @scpeters)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/355#-MGsvMMaBTsZQE7lLGQS:-MGtPDmj5Q7Qj0hGni5o:b-wf9t5j) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I guess I'm confused - why are you implementing this before #293 lands?

It seems like you'd need scaffolding that would go away once we have it, and there are also conversion issues that need to be solved as part of #293.

In #278, the way we formatted the dates (both #293 and #342), it seems like it could happen in parallel, but seeing y'all's discussion below, perhaps we'd want to wait?
</blockquote></details>

OK See discussion below.

---


<!-- Sent from Reviewable.io -->

2020-09-10 19:27 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey and @scpeters)

___
*[src/Model.cc, line 722 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGtS5g59qJtZoOS8GqZ:-MGtS5g59qJtZoOS8Gq_:b-j06vue) ([raw file](https://github.com/osrf/sdformat/blob/6659e833edb965eabc03d86785bd9c69cdf5637a/src/Model.cc#L722)):*
> ```cpp
>   {
>     return nextModel->ModelByName(_name.substr(index + 2));
>   }
> ```

Per above, we should extend the composition proposal to talk about the up-conversion process.

Basically, what Addisu said: we should try to turn flattened models into nested models for *declarations*.

References would only be unflattened within the "unnested" elements (e.g. if link `M1::B` refers to `M1::C`, then it would then reference `C` inside of `M1`).

The hoisting / unflattening could happen prior to any semantic parsing, and then the unflattened XML can be handed to the nominal 1.8 parser.

One minor edge case:

```
<!-- 1.7 -->
<link name="M1::B">
   <pose relative_to="M2::B"/>
</link>
<link name="M2::B"/>
```
-->
```
<!-- 1.8 -->
<model name="M1">
   <link name="B">
     <pose relative_to="M2::B"/>  <!-- Invalid! -->
   </link>
</model>
<model name="M2">
  <link name="B"/>
</model>
```


<!-- Sent from Reviewable.io -->

2020-09-10 19:29 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[src/Model.cc, line 722 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGtS5g59qJtZoOS8GqZ:-MGtUcmO5sHgCU9sLxlz:b38xe53) ([raw file](https://github.com/osrf/sdformat/blob/6659e833edb965eabc03d86785bd9c69cdf5637a/src/Model.cc#L722)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per above, we should extend the composition proposal to talk about the up-conversion process.

Basically, what Addisu said: we should try to turn flattened models into nested models for *declarations*.

References would only be unflattened within the "unnested" elements (e.g. if link `M1::B` refers to `M1::C`, then it would then reference `C` inside of `M1`).

The hoisting / unflattening could happen prior to any semantic parsing, and then the unflattened XML can be handed to the nominal 1.8 parser.

One minor edge case:

```
<!-- 1.7 -->
<link name="M1::B">
   <pose relative_to="M2::B"/>
</link>
<link name="M2::B"/>
```
-->
```
<!-- 1.8 -->
<model name="M1">
   <link name="B">
     <pose relative_to="M2::B"/>  <!-- Invalid! -->
   </link>
</model>
<model name="M2">
  <link name="B"/>
</model>
```
</blockquote></details>

Working: I will do this shortly.


<!-- Sent from Reviewable.io -->

2020-09-10 20:32 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @scpeters)

___
*[src/Model.cc, line 722 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGtS5g59qJtZoOS8GqZ:-MGthwmr5upMD4a41cf_:b-d2eejz) ([raw file](https://github.com/osrf/sdformat/blob/6659e833edb965eabc03d86785bd9c69cdf5637a/src/Model.cc#L722)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I will do this shortly.
</blockquote></details>

Done: Filed https://github.com/osrf/sdf_tutorials/pull/41


<!-- Sent from Reviewable.io -->

2020-10-15 18:41 UTC, EricCousineau-TRI commented
Superseded by https://github.com/osrf/sdformat/pull/381

2020-10-22 19:16 UTC, scpeters commented
> > _[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)_ status: all files reviewed, 3 unresolved discussions (waiting on @azeey and @scpeters)
> 
> _[src/Model.cc, line 719 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGpOgXB42F54tfaWTji:-MGtOzbG6yRgZ6BYSh58:b45x1bw) ([raw file](https://github.com/osrf/sdformat/blob/6659e833edb965eabc03d86785bd9c69cdf5637a/src/Model.cc#L719)):_
> 
> Previously, azeey (Addisu Z. Taddese) wrote…
> Per f2f, it should be OK to be temporarily backwards-incompatible in code, given that:
> 
> * We ensure that "master" is clearly denoted as unstable in the README
> * The breakage is shown in a unittest with a clear comment.
> * There's a TODO to resolve the comment afterwards.

I'll do this

2020-10-26 21:13 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/355#-MGsvm4x7H8nC8QRR4u2:-MKI6MkF6aBK9hs7Vq3S:b-gwb7kg) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

In the overview, can you state (above the text explanation) that this is gearing towards #342?
</blockquote></details>

I've added this to the PR description.

---
___
*[src/Model.cc, line 719 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGpOgXB42F54tfaWTji:-MKakRvEDA3I-QQqW2Mw:b-6aqsgq) ([raw file](https://github.com/osrf/sdformat/blob/c44f822ee8869c1ab0841f465d4b6a76dc597d50/src/Model.cc#L719)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I'll do this 
</blockquote></details>

I've added a unit test showing the breakage with TODOs in 93658c3

I forgot to update the readme, will do that next


<!-- Sent from Reviewable.io -->

2020-10-26 21:26 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[src/Model.cc, line 719 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGpOgXB42F54tfaWTji:-MKanEdI6Z7Sf-2sKbRq:b-gjrvbk) ([raw file](https://github.com/osrf/sdformat/blob/c44f822ee8869c1ab0841f465d4b6a76dc597d50/src/Model.cc#L719)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I've added a unit test showing the breakage with TODOs in 93658c3

I forgot to update the readme, will do that next
</blockquote></details>

readme in 8d3fdf2, this should be done by now
___
*[test/integration/model_dom.cc, line 291 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGsdR4t3Q2ykgpRBGmM:-MKanLTV5j2TR2s141yY:b-u9np4i) ([raw file](https://github.com/osrf/sdformat/blob/c44f822ee8869c1ab0841f465d4b6a76dc597d50/test/integration/model_dom.cc#L291)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

FYI, you could compare this against `innerModel->LinkByIndex(0)` to be more precise.
</blockquote></details>

added some more expectations in 026434e


<!-- Sent from Reviewable.io -->

2020-10-26 23:35 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[test/integration/model_dom.cc, line 291 at r2](https://reviewable.io/reviews/osrf/sdformat/355#-MGsdR4t3Q2ykgpRBGmM:-MKbFj2X4rVWWCQ6cn8x:b-7op5ud) ([raw file](https://github.com/osrf/sdformat/blob/c44f822ee8869c1ab0841f465d4b6a76dc597d50/test/integration/model_dom.cc#L291)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

added some more expectations in 026434e
</blockquote></details>

I added them incorrectly, fixed in fef1d57


<!-- Sent from Reviewable.io -->

2020-10-27 16:45 UTC, azeey requested changes
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @scpeters)

___
*[test/sdf/partially_flattened.sdf, line 2 at r4](https://reviewable.io/reviews/osrf/sdformat/355#-MKevX_2E-HhzhVGB9vn:-MKevX_2E-HhzhVGB9vo:bek3iar) ([raw file](https://github.com/osrf/sdformat/blob/fef1d57134cb772921b30abe02f325401c0517da/test/sdf/partially_flattened.sdf#L2)):*
> ```
> <sdf version='1.7'>
>   <model name='MP'>
> ```

I assume this was generated from an existing "included" model. Can you add a comment about which files were used to generate this?


<!-- Sent from Reviewable.io -->

2020-10-27 16:46 UTC, azeey approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with minor comment.

> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355#-:-MKewxJ80_8XY7VI1RJW:b-ij5egr)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @scpeters)



<!-- Sent from Reviewable.io -->

2020-10-27 21:53 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/355#-MGsvm4x7H8nC8QRR4u2:-MKg1uji2TtaV78lsw_B:b-896fix) (no related file):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I've added this to the PR description.
</blockquote></details>

Done.

---
___
*[test/sdf/partially_flattened.sdf, line 2 at r4](https://reviewable.io/reviews/osrf/sdformat/355#-MKevX_2E-HhzhVGB9vn:-MKg1wnm-v3NyPSvxNAT:bl0xkk8) ([raw file](https://github.com/osrf/sdformat/blob/fef1d57134cb772921b30abe02f325401c0517da/test/sdf/partially_flattened.sdf#L2)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I assume this was generated from an existing "included" model. Can you add a comment about which files were used to generate this?
</blockquote></details>

I copied it directly from your comment: https://github.com/osrf/sdformat/pull/355#pullrequestreview-485492932


<!-- Sent from Reviewable.io -->

2020-10-29 18:43 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/355#-MKperAl-6PNZmF4k1yK:-MKperAl-6PNZmF4k1yL:btwanp1) (no related file):*
Steve will incorporate forward-porting of this PR:
https://github.com/osrf/sdformat/pull/399

---


<!-- Sent from Reviewable.io -->

2020-10-30 07:10 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355)* status: 10 of 16 files reviewed, 3 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/355#-MKperAl-6PNZmF4k1yK:-MKsKVIq7o0JLIwEyEEX:bb6un1j) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Steve will incorporate forward-porting of this PR:
https://github.com/osrf/sdformat/pull/399
</blockquote></details>

Done

---
___
*[test/sdf/partially_flattened.sdf, line 2 at r4](https://reviewable.io/reviews/osrf/sdformat/355#-MKevX_2E-HhzhVGB9vn:-MKsK_2vAZgak-NV8CEL:b-24t7u1) ([raw file](https://github.com/osrf/sdformat/blob/fef1d57134cb772921b30abe02f325401c0517da/test/sdf/partially_flattened.sdf#L2)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I copied it directly from your comment: https://github.com/osrf/sdformat/pull/355#pullrequestreview-485492932
</blockquote></details>

after cherry-picking #399, I removed this file and changed the test to use nested_model_with_frames_expected.sdf, which now has a partially flattened nested model


<!-- Sent from Reviewable.io -->

2020-10-30 10:48 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 8 of 10 files at r1, 1 of 2 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355#-:-MKt6r6R8DbaWdtnd0co:b-uwkowd)* status: all files reviewed, 1 unresolved discussion (waiting on @azeey)



<!-- Sent from Reviewable.io -->

2020-10-30 14:52 UTC, azeey approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/355#-:-MKtzOV78N7l37IKzoJ8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[test/sdf/partially_flattened.sdf, line 2 at r4](https://reviewable.io/reviews/osrf/sdformat/355#-MKevX_2E-HhzhVGB9vn:-MKtzAnq0Felevo3UIhE:bxnofk5) ([raw file](https://github.com/osrf/sdformat/blob/fef1d57134cb772921b30abe02f325401c0517da/test/sdf/partially_flattened.sdf#L2)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

after cherry-picking #399, I removed this file and changed the test to use nested_model_with_frames_expected.sdf, which now has a partially flattened nested model
</blockquote></details>

Ok. Thanks!


<!-- Sent from Reviewable.io -->

2020-10-30 15:19 UTC, scpeters commented
I'm going to squash everything but #399 and then rebase and merge the two commits

2020-10-30 16:05 UTC, merged