Allow "drilling down" into nested model frames
osrf/sdformat pull request #381
Opened 2020-10-01 18:07 UTC by azeey

This a draft PR that adds functionality to allow drilling down into nested models with the `::` syntax. This also makes included models work as nested models

Resolves #293, #284
This builds on top of #355

2020-10-01 18:54 UTC, EricCousineau-TRI commented
Per f2f:

* AT, SP: Semantic pose API, breaking encapsulation?
    * (1) Add arg to ResolvePose() and ResolveXyzAxis() for how many levels up
    * (2) Add SemanticPose.GetView(Level)
      * Have //joint/axis/xyz be expressed as SemanticPose or "SemanticOrientation"
    * (3) Bake "upwards references" into string lookups in ResolvePose() and ResolveXyzAxis()
    * (4) Pass SemanticPose objects directly into `ResolvePose()` and `ResolveXyzAxis()`

2020-10-08 19:09 UTC, EricCousineau-TRI commented
Per f2f:

* My comment is, would be nice to collapse `SemanticPose x {ElementType}` to just `SelemanticPose x SemanticPose` (or something that has a name)
* libsdformat11 will be able to parse SDFormat 1.7 files that couldn't have been parsed in <=libsdformat10. We deem that fine, and place the burden on downstream to use <=libsdformat10 to inform how to use models, 'cause libsdformat11 is a strict superset.

2020-10-12 21:21 UTC, scpeters commented on src/ScopedGraph.hh
> +class FrameAttachedToGraph;
I think these are both `struct`s, not `class`es

2020-10-14 20:34 UTC, EricCousineau-TRI commented on include/sdf/JointAxis.hh
> +        const sdf::SemanticPose &_scope) const;
nit Why `_scope` instead of `_semPose`?

2020-10-15 17:47 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 1 of 60 files reviewed, 3 unresolved discussions (waiting on @azeey)



<!-- Sent from Reviewable.io -->

2020-10-15 17:58 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 10 files at r1, 10 of 41 files at r2, 1 of 16 files at r6, 7 of 24 files at r7.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 20 of 60 files reviewed, 11 unresolved discussions (waiting on @azeey)

___
*[Migration.md, line 27 at r4](https://reviewable.io/reviews/osrf/sdformat/381#-MJhN2NgEWtq7xUEtPUC:-MJhN2Nh3n0OpoceGwDi:b-hgv3zi) ([raw file](https://github.com/osrf/sdformat/blob/2cbe572f8259bd760beffdd8a9fdb360d16b5638/Migration.md#L27)):*
> ```Markdown
> 1. **sdf/Model.hh**: the following methods now accept nested names
>       that can begin with a sequence of nested model names separated
>       by `::` and may end with the name of an object of the specified type.
> ```

nit Should this mention that it's relative the model's scope?
___
*[include/sdf/JointAxis.hh, line 273 at r6](https://reviewable.io/reviews/osrf/sdformat/381#-MJ8sqgfhoOXkEIHoV7F-r6-273:-MJhNDEWALYbJyXTbLKq:b-26i7z8) ([raw file](https://github.com/osrf/sdformat/blob/4d86a91334a0002dc3862df09d8ec0a0aa187a4a/include/sdf/JointAxis.hh#L273)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why `_scope` instead of `_semPose`?
</blockquote></details>

OK Was removed in r6, marking myself satisfied.
___
*[include/sdf/Model.hh, line 175 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhNSL92GOn1bpDP8t6:-MJhNSL92GOn1bpDP8t7:b-dtbyvg) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/Model.hh#L175)):*
> ```Hack
>     /// \brief Get whether a joint name exists.
>     /// \param[in] _name Name of the joint to check.
>     /// To check for a joint in a nested model, prefix the link name with
> ```

nit "link" is copy-pasta'd here
___
*[include/sdf/SemanticPose.hh, line 43 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhNaL-2cVyd4uKdz-J:-MJhNaL-2cVyd4uKdz-K:b-ignq6o) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/SemanticPose.hh#L43)):*
> ```Hack
> 
>   // Forward declare private data class.
>   class Model;
> ```

nit Why are these forward declarations necessary here?

At least in the current diff (base - r7), I don't see why these're here.
___
*[src/FrameSemantics.cc, line 224 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhNx6pCGpproW9qEw1:-MJhNx6pCGpproW9qEw2:biv96id) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L224)):*
> ```cpp
>     return errors;
>   }
>   else if (_model->LinkCount() < 1 && _model->ModelCount() < 1 &&
> ```

nit Why `< 1` instead of just `== 0`?

(soz, pre-existing defect, but curious)
___
*[src/FrameSemantics.cc, line 373 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhOPEbE8UOtfWMEm93:-MJhOPEbE8UOtfWMEm94:b9tjgcl) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L373)):*
> ```cpp
> 
>   // identify canonical link, which may be nested
>   auto canonicalLinkAndName = modelCanonicalLinkAndRelativeName(_model);
> ```

nit Consider using a structured binding here?
```
const auto [link, name] = ...
```
___
*[src/FrameSemantics.cc, line 390 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhOG_i8JYMOjj-2my0:-MJhOG_i8JYMOjj-2my1:b-glwpj7) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L390)):*
> ```cpp
>         {
>           // The canonical link was not found, but the model could have a
>           // decendant that has a static model, so simply create an edge to the
> ```

nit Spelling "descendant"
___
*[src/FrameSemantics.cc, line 794 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhOkUT-0wl36I22ESW:-MJhOkUT-0wl36I22ESX:b9t556l) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L794)):*
> ```cpp
>     }
> 
>     ignition::math::Pose3d X_RM = nestedModel->RawPose();
> ```

nit Can you forward reference (or hoist) the comments below which defines these frames?
___
*[src/FrameSemantics.cc, line 971 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhP4LQ1UHGBsllL6Xb:-MJhP4LQ1UHGBsllL6Xc:bwsvvvi) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L971)):*
> ```cpp
>     }
> 
>     ignition::math::Pose3d X_RM = model->RawPose();
> ```

This looks like a copy-pasta of the stanza above.

Can this be factored out into a separate function?
___
*[src/cmd/cmdsdformat.rb.in, line 44 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPNv1-m2bszXfjGub:-MJhPNv1-m2bszXfjGuc:b-fb7x47) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/cmd/cmdsdformat.rb.in#L44)):*
> ```
>                        "  -d [ --describe ] [SPEC VERSION] Print the aggregated SDFormat spec description. Default version (@SDF_PROTOCOL_VERSION@).\n" +
>                        "  -p [ --print ] arg               Print converted arg.\n" +
>                        "  -g [ --graph ] <pose, frame> arg   Print the PoseRelativeTo or FrameAttachedTo graph.\n" +
> ```

This is now exposing private details in a public interface (the CLI).

Can you note that this is for advanced-use only, and may be subject to change w/o any promise of stability?


<!-- Sent from Reviewable.io -->

2020-10-15 18:03 UTC, EricCousineau-TRI reviewed
Made an initial foray in the code - looking good thus far - PTAL!

> Reviewed 4 of 24 files at r7.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381#-:-MJhQVRj38b54mwOO4Wv:bcdljyi)* status: 24 of 60 files reviewed, 15 unresolved discussions (waiting on @azeey)

___
*[src/Model.cc, line 242 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPfI8EZ5pMXN0foA6:-MJhPfI8EZ5pMXN0foA7:b-bmxgk9) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L242)):*
> ```cpp
>   }
> 
>   bool modelFile = false;
> ```

nit This variable name is ambiguous.

At a minimum, can you add a clarifying comment?
e.g. "This model is defined at the root of the given XML model file"
or rename it? e.g. `is_model_defined_at_root_of_xml_model_file`?
___
*[src/Model.cc, line 244 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPbiLC2vmD_-0cgtq:-MJhPbiLC2vmD_-0cgtr:bqod5oi) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L244)):*
> ```cpp
>   bool modelFile = false;
> 
>   // if (!this->dataPtr->poseGraph)
> ```

nit Dead code?
___
*[src/Model.cc, line 248 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPd5Z2S7HAqt-ZJCJ:-MJhPd5Z2S7HAqt-ZJCK:bqod5oi) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L248)):*
> ```cpp
>   if (parentElem && parentElem->GetName() == "sdf")
>   {
>     // std::cout << "Creating owned graphs for " << this->Name() << std::endl;
> ```

nit Dead code?
___
*[src/Model.cc, line 590 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPweX9-grwZPVKxes:-MJhPweX9-grwZPVKxet:bev6len) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L590)):*
> ```cpp
> const Frame *Model::FrameByName(const std::string &_name) const
> {
>   auto index = _name.rfind("::");
> ```

Is there a way to move these splitting semantics to separate function?

At least for string parsing?

Here's a (crappy) way of how we did this Anzu for model directives (which have now been hoisted to Drake):
https://github.com/RobotLocomotion/drake/blob/cd4890d564d1c44107b2c32b8996346eb2e61a23/multibody/parsing/scoped_names.h#L43-L58


<!-- Sent from Reviewable.io -->

2020-10-15 18:16 UTC, scpeters requested changes
> Reviewed 10 of 10 files at r1, 3 of 41 files at r2, 1 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 28 of 60 files reviewed, 16 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/SemanticPose.hh, line 43 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhNaL-2cVyd4uKdz-J:-MJhS1911DMLcttQynzN:b-2s7rpu) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/SemanticPose.hh#L43)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why are these forward declarations necessary here?

At least in the current diff (base - r7), I don't see why these're here.
</blockquote></details>

yeah, looks like they're left over
___
*[include/sdf/SemanticPose.hh, line 93 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhTO044QikZ5AkfVBM:-MJhTO044QikZ5AkfVBN:b-byuths) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/SemanticPose.hh#L93)):*
> ```Hack
>         const sdf::ScopedGraph<sdf::PoseRelativeToGraph> &_graph);
> 
>     private: SemanticPose(
> ```

need doxygen for this new constructor to describe the new `_name` parameter


<!-- Sent from Reviewable.io -->

2020-10-15 19:46 UTC, scpeters requested changes
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 28 of 60 files reviewed, 24 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/Frame.hh, line 139 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhmZZzBDW6mJNybdK4:-MJhmZZzBDW6mJNybdK5:b-qllf6q) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/Frame.hh#L139)):*
> ```Hack
>     /// FrameAttachedToGraph. If this is in a __model__ scope, it returns
>     /// the name of a link. In the world scope, it returns the name of a
>     /// model or the world.
> ```

this documentation needs to be updated as this method no longer returns a model name
___
*[include/sdf/Types.hh, line 72 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhUHFOE9vLrkvacZ25:-MJhUHFPAzd75aAku4L4:bbuc4cf) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/Types.hh#L72)):*
> ```Hack
> 
>   SDFORMAT_VISIBLE
>   bool endswith(const std::string &_a, const std::string &_b);
> ```

need doxygen
___
*[src/ign.cc, line 166 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhlHY45Q08-TK7z-vE:-MJhlHY45Q08-TK7z-vF:b-6gcyfd) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/ign.cc#L166)):*
> ```cpp
> //////////////////////////////////////////////////
> // cppcheck-suppress unusedFunction
> extern "C" SDFORMAT_VISIBLE int cmdGraph(
> ```

could add a test for this in `ign_TEST.cc`
___
*[src/ign.cc, line 219 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhkj8x03xjSoAe40Ta:-MJhkj8x03xjSoAe40Tb:bspkqs) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/ign.cc#L219)):*
> ```cpp
>     }
>     std::cout << graph.Graph() << std::endl;
>   }
> ```

add an `else` statement with an error message explaining that `pose` or `frame` are the only valid arguments?
___
*[src/Types.cc, line 74 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhUiJ9AOafbfsjCmI8:-MJhUiJ9AOafbfsjCmI9:b65uih0) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Types.cc#L74)):*
> ```cpp
> 
> //////////////////////////////////////////////////
> bool endswith(const std::string& _a, const std::string& _b)
> ```

should add a unit test for this to Types_TEST.cc
___
*[src/Types.cc, line 90 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhUnI52Vlqs4jDabJa:-MJhUnI52Vlqs4jDabJb:b65uih0) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Types.cc#L90)):*
> ```cpp
> 
> /////////////////////////////////////////////////
> std::ostream &operator<<(std::ostream &_out, const sdf::Errors &_errs)
> ```

should add a unit test for this to Types_TEST.cc
___
*[src/World.cc, line 398 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhgIfVEp40aC-0AyGE:-MJhgIfVEp40aC-0AyGF:b-9rcxfr) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/World.cc#L398)):*
> ```cpp
>                                 setPoseRelativeToGraphErrors.end());
>     errors.insert(errors.end(), setPoseRelativeToGraphErrors.begin(),
>                                 setPoseRelativeToGraphErrors.end());
> ```

these two new lines are duplicates of the lines above; I think they aren't needed
___
*[src/cmd/cmdsdformat.rb.in, line 44 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhW91d79Bv0G-uQVf3:-MJhW91d79Bv0G-uQVf4:bhe4w9r) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/cmd/cmdsdformat.rb.in#L44)):*
> ```
>                        "  -d [ --describe ] [SPEC VERSION] Print the aggregated SDFormat spec description. Default version (@SDF_PROTOCOL_VERSION@).\n" +
>                        "  -p [ --print ] arg               Print converted arg.\n" +
>                        "  -g [ --graph ] <pose, frame> arg   Print the PoseRelativeTo or FrameAttachedTo graph.\n" +
> ```

nit: alphabetize the `--` commands (i.e. move this before `--print`) and remove `arg` (i.e. `-g [ --graph ] <pose, frame> arg Print ...`)


<!-- Sent from Reviewable.io -->

2020-10-19 05:25 UTC, scpeters requested changes
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 28 of 60 files reviewed, 32 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[src/Model.cc, line 831 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyAKGW3UOlPe0kX_xD:-MJyAKGX5U3rbNALUkqA:bw4yx79) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L831)):*
> ```cpp
>   // Pass an empty string for the defaultResolveTo argument so that it can
>   // resolve to the scope vertex regardless of whether this model is a
>   // standalone model or part of a world.
> ```

this comment doesn't make sense to me
___
*[src/parser.cc, line 868 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyAgUQ1YUYiUsi6ef8:-MJyAgUQ1YUYiUsi6ef9:b-cfrxvh) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L868)):*
> ```cpp
>           _errors.push_back({ErrorCode::ATTRIBUTE_INVALID,
>               "'__root__' is reserved; it cannot be used as a value of "
>               "attribute [" + p->GetKey() + "]"});
> ```

I know that we have reserved `__.*__` from being used in attribute names, but this will currently generate an error if any attribute (even a custom attribute) has the value `__root__`. This seems too strict to me
___
*[src/parser.cc, line 1083 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyBbKf8-V2onmU3a19:-MJyBbKf8-V2onmU3a1A:bt0z1xq) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L1083)):*
> ```cpp
>         // a core feature of SDF, and not a hack that that parser handles
>         // includeSDF->Root()->GetFirstElement()->SetInclude(
>         // elemXml->Attribute("filename"));
> ```

I wonder if we want to revisit this TODO during this development cycle?
___
*[src/parser.cc, line 1428 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyFKBa2XWnS7hiyRN7:-MJyFKBa2XWnS7hiyRN8:ba8al3e) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L1428)):*
> ```cpp
>         auto index = _name.find(model->Name() + "::");
>         std::string nameToCheck = _name;
>         if (index != std::string::npos)
> ```

this check doesn't seem quite right; it could find the model name anywhere in the string, when I think it should only compare it to the very beginning of `_name`. In fact, I don't think it needs to iterate over all the models; couldn't it extract the substring before the first `::` and call `ModelByName` on that?
___
*[src/parser.cc, line 1667 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyG29o6E6L2dDExVTf:-MJyG29o6E6L2dDExVTg:b-79eyt0) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L1667)):*
> ```cpp
>                   << std::endl;
>       }
>       std::cout << graph.Graph() << std::endl;
> ```

nit: remove debugging message?
___
*[src/parser.cc, line 1697 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyG84k6WH09IC1_DI1:-MJyG84k6WH09IC1_DI2:b-79eyt0) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L1697)):*
> ```cpp
>                   << std::endl;
>       }
>       std::cout << graph.Graph() << std::endl;
> ```

nit: remove debugging message?
___
*[test/integration/joint_dom.cc, line 792 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJzF6tD8SgaPzUnVT3H:-MJzF6tD8SgaPzUnVT3I:b9ohsjq) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/test/integration/joint_dom.cc#L792)):*
> ```cpp
>     ASSERT_NE(nullptr, j1);
>     EXPECT_EQ("M1::L1", j1->ParentLinkName());
>     EXPECT_EQ("L1", j1->ChildLinkName());
> ```

I think we could also test the `Joint::Resolve*Link` functions here. Please consider cherry-picking https://github.com/scpeters/sdformat/commit/a9025a2c94d6e2ede90041271b75f856389b4579
___
*[test/sdf/joint_nested_parent_child.sdf, line 8 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJiTxgp78wowhbfHYdI:-MJiTxgp78wowhbfHYdJ:b-g2pnne) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/test/sdf/joint_nested_parent_child.sdf#L8)):*
> ```
>       each link's pose is displaced along the z-axis,
>       frames are displaced along the y-axis,
>       and joints are displaced along the x-axis.
> ```

this comment block is not accurate


<!-- Sent from Reviewable.io -->

2020-10-19 09:28 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 28 of 60 files reviewed, 32 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[src/cmd/cmdsdformat.rb.in, line 44 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhW91d79Bv0G-uQVf3:-MJzvq1i4RiMc96NV-T1:b-2kboqi) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/cmd/cmdsdformat.rb.in#L44)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: alphabetize the `--` commands (i.e. move this before `--print`) and remove `arg` (i.e. `-g [ --graph ] <pose, frame> arg Print ...`)
</blockquote></details>

oops, don't remove `arg`; we still need that


<!-- Sent from Reviewable.io -->

2020-10-23 21:30 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 28 of 60 files reviewed, 22 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[Migration.md, line 27 at r4](https://reviewable.io/reviews/osrf/sdformat/381#-MJhN2NgEWtq7xUEtPUC:-MKFzcQ64vW3ItBp3uU7:b-93qmm2) ([raw file](https://github.com/osrf/sdformat/blob/2cbe572f8259bd760beffdd8a9fdb360d16b5638/Migration.md#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should this mention that it's relative the model's scope?
</blockquote></details>

Done in f4b40983
___
*[include/sdf/Frame.hh, line 139 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhmZZzBDW6mJNybdK4:-MKG-LJG4Sh07KNaEayM:b-93qmm2) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/Frame.hh#L139)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

this documentation needs to be updated as this method no longer returns a model name
</blockquote></details>

Done in f4b40983
___
*[include/sdf/JointAxis.hh, line 273 at r6](https://reviewable.io/reviews/osrf/sdformat/381#-MJ8sqgfhoOXkEIHoV7F-r6-273:-MKG-UDvEm9g6RShzhE8:bc7rde9) ([raw file](https://github.com/osrf/sdformat/blob/4d86a91334a0002dc3862df09d8ec0a0aa187a4a/include/sdf/JointAxis.hh#L273)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Was removed in r6, marking myself satisfied.
</blockquote></details>

Yes, passing a `SemanticPose` object turned out to be a lot more complicated than I thought, so I removed it. We might consider adding it back later on.
___
*[include/sdf/Model.hh, line 312 at r4](https://reviewable.io/reviews/osrf/sdformat/381#-MJ8sqgeCY1jh0vVyV0j-r4-312:-MKG45se1Qv4kIeEMcin:bs2vkr0) ([raw file](https://github.com/osrf/sdformat/blob/2cbe572f8259bd760beffdd8a9fdb360d16b5638/include/sdf/Model.hh#L312)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

need doxygen for this
</blockquote></details>

Done in 4e368f19
___
*[include/sdf/Model.hh, line 175 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhNSL92GOn1bpDP8t6:-MKMHpqS0Uxql-gPCCG9:bftdria) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/Model.hh#L175)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "link" is copy-pasta'd here
</blockquote></details>

Done in b1589980.
___
*[include/sdf/Model.hh, line 309 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MKG48-3Ef71_IN0Jobi:-MKG48-3Ef71_IN0Jobj:b1jjmro) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/Model.hh#L309)):*
> ```Hack
>     /// \return Error if graph pointer is invalid.
>     private: sdf::Errors SetPoseRelativeToGraph(
>         sdf::ScopedGraph<PoseRelativeToGraph> _graph);
> ```

@scpeters Do we still need to return `sdf::Errors` from this? The `SetPoseRelativeToGraph` of other DOM objects returns `void`.
___
*[include/sdf/SemanticPose.hh, line 43 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhNaL-2cVyd4uKdz-J:-MKG5sCOEI1ZB3Rj5r58:b-oyhq9h) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/SemanticPose.hh#L43)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

yeah, looks like they're left over
</blockquote></details>

Yes, they're left over from when I had the Resolve functions with DOM object parameters. Removed in ea08d4fb
___
*[include/sdf/SemanticPose.hh, line 93 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhTO044QikZ5AkfVBM:-MKG68Z-DSkTmaPVdSaq:boyjhaw) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/SemanticPose.hh#L93)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

need doxygen for this new constructor to describe the new `_name` parameter
</blockquote></details>

Added in 9810c10f
___
*[include/sdf/Types.hh, line 72 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhUHFOE9vLrkvacZ25:-MKG6eWK8hk6ShKROmeN:b-iqqx15) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/Types.hh#L72)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

need doxygen
</blockquote></details>

I ended up not needing this function, so I removed it in ea08d4fb
___
*[src/FrameSemantics.cc, line 224 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhNx6pCGpproW9qEw1:-MKG73kmChbreY4cXbFv:b4tue5t) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L224)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why `< 1` instead of just `== 0`?

(soz, pre-existing defect, but curious)
</blockquote></details>

Not sure. I think they can be `==0`.
___
*[src/FrameSemantics.cc, line 373 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhOPEbE8UOtfWMEm93:-MKMKN_gDy6aoCOOIBx8:bftdria) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L373)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider using a structured binding here?
```
const auto [link, name] = ...
```
</blockquote></details>

Done in b1589980.
___
*[src/FrameSemantics.cc, line 390 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhOG_i8JYMOjj-2my0:-MKMHywC7vSg66s3eV0D:bftdria) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L390)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Spelling "descendant"
</blockquote></details>

Done in b1589980.
___
*[src/FrameSemantics.cc, line 794 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhOkUT-0wl36I22ESW:-MKLvUxr9rk6GDFzAXYB:b-ljvwdz) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L794)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you forward reference (or hoist) the comments below which defines these frames?
</blockquote></details>

Refactored code that handles PlacementFrame into a function in 47bdf84e 
___
*[src/FrameSemantics.cc, line 971 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhP4LQ1UHGBsllL6Xb:-MKLvdp5857Qnxxcj7bu:b-r6rxmy) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L971)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This looks like a copy-pasta of the stanza above.

Can this be factored out into a separate function?
</blockquote></details>

Done in 47bdf84e 
___
*[src/ign.cc, line 219 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhkj8x03xjSoAe40Ta:-MKMI0-8EfE1bYEGoRDA:b-6wxpdy) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/ign.cc#L219)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

add an `else` statement with an error message explaining that `pose` or `frame` are the only valid arguments?
</blockquote></details>

Done in b1589980 .
___
*[src/Model.cc, line 242 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPfI8EZ5pMXN0foA6:-MKLyZkh0Xbm-d3ctIfw:bdbiyvv) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L242)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This [...]

2020-10-23 23:33 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 28 of 60 files reviewed, 22 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[src/parser.cc, line 868 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyAgUQ1YUYiUsi6ef8:-MKMcq4p73OPc6IMR_D5:bplefgf) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L868)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I know that we have reserved `__.*__` from being used in attribute names, but this will currently generate an error if any attribute (even a custom attribute) has the value `__root__`. This seems too strict to me
</blockquote></details>

Since custom attributes are handled before the code gets here, it will not generate an error. But I could check only the `relative_to`, `attached_to`, and `placement_frame` attributes since those are the only attributes that take frame names. I guess we probably need to check `//include/placement_frame`, `//joint/parent`, and `//joint/child` as well.
___
*[src/parser.cc, line 1428 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyFKBa2XWnS7hiyRN7:-MKMaVwn7UxhtMfZ_OE7:b-g9eaoi) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L1428)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

this check doesn't seem quite right; it could find the model name anywhere in the string, when I think it should only compare it to the very beginning of `_name`. In fact, I don't think it needs to iterate over all the models; couldn't it extract the substring before the first `::` and call `ModelByName` on that?
</blockquote></details>

Yeah, you're right. I added a failing test demonstrating the problem in 89f95010 and added the fix per your suggestion in 4850674e 
___
*[src/Types.cc, line 90 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhUnI52Vlqs4jDabJa:-MKMlajk7XKivYsLVRMx:b-2n1ny0) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Types.cc#L90)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

should add a unit test for this to Types_TEST.cc
</blockquote></details>

Done in d552382c.


<!-- Sent from Reviewable.io -->

2020-10-27 00:50 UTC, scpeters requested changes
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 13 of 62 files reviewed, 9 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/Model.hh, line 309 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MKG48-3Ef71_IN0Jobi:-MKbVxdB4yE9FdKIKuBt:bs8ixun) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/Model.hh#L309)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

@scpeters Do we still need to return `sdf::Errors` from this? The `SetPoseRelativeToGraph` of other DOM objects returns `void`.
</blockquote></details>

in [version 10.0.0](https://github.com/osrf/sdformat/blob/sdformat10_10.0.0/src/Model.cc#L698-L709), it returns errors in case it is passed a `weak_ptr` that it can't resolve

if the `ScopedGraph` doesn't have this same problem, then there's no reason to return an error. this branch currently [returns an error](https://github.com/azeey/sdformat/blob/drill_down/src/Model.cc#L749-L7590), so remove it if you think that is ok
___
*[src/parser.cc, line 868 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyAgUQ1YUYiUsi6ef8:-MKbTmBr3_AuXxvBYuF6:ba6xbg3) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L868)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Since custom attributes are handled before the code gets here, it will not generate an error. But I could check only the `relative_to`, `attached_to`, and `placement_frame` attributes since those are the only attributes that take frame names. I guess we probably need to check `//include/placement_frame`, `//joint/parent`, and `//joint/child` as well.
</blockquote></details>

I prefer checking the specific attributes and elements that you listed
___
*[src/parser.cc, line 1428 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyFKBa2XWnS7hiyRN7:-MKbSZSFCPkYW2dGZ2jT:bb6ywmx) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L1428)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Yeah, you're right. I added a failing test demonstrating the problem in 89f95010 and added the fix per your suggestion in 4850674e 
</blockquote></details>

LGTM
___
*[src/cmd/cmdsdformat.rb.in, line 44 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPNv1-m2bszXfjGub:-MKbSwAJ8DET7cWdY3dD:bzd5lq2) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/cmd/cmdsdformat.rb.in#L44)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Yeah, this was useful during development. If you guys think it should be removed, I'd be okay with it.
</blockquote></details>

I like the feature; it looks good with the added description.


<!-- Sent from Reviewable.io -->

2020-10-27 22:39 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 12 of 65 files reviewed, 8 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/Model.hh, line 309 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MKG48-3Ef71_IN0Jobi:-MKf0oFK1qsg7Vxtoz-L:b-v3c5r3) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/include/sdf/Model.hh#L309)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

in [version 10.0.0](https://github.com/osrf/sdformat/blob/sdformat10_10.0.0/src/Model.cc#L698-L709), it returns errors in case it is passed a `weak_ptr` that it can't resolve

if the `ScopedGraph` doesn't have this same problem, then there's no reason to return an error. this branch currently [returns an error](https://github.com/azeey/sdformat/blob/drill_down/src/Model.cc#L749-L7590), so remove it if you think that is ok
</blockquote></details>

Done in 60a903d.
___
*[src/ign.cc, line 166 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhlHY45Q08-TK7z-vE:-MKfkGJS-6TpvZ_Wpyhx:b-wdertd) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/ign.cc#L166)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

could add a test for this in `ign_TEST.cc`
</blockquote></details>

Done in de319b9
___
*[src/parser.cc, line 868 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyAgUQ1YUYiUsi6ef8:-MKgC7VnEoeHlTw-eh3w:b-xno9c1) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L868)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I prefer checking the specific attributes and elements that you listed
</blockquote></details>

Done in 2a21634. I have also added `//model/[@canonical_link]` and //sensor/imu/orientation_reference_frame/custom_rpy/[@parent_frame].


<!-- Sent from Reviewable.io -->

2020-10-28 02:00 UTC, scpeters requested changes
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 12 of 65 files reviewed, 9 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[src/parser.cc, line 844 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgqCGQ01wZ66mObSq4:-MKgqCGQ01wZ66mObSq5:b-e2eely) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/src/parser.cc#L844)):*
> ```cpp
> 
>   // A list of attributes where a frame name is referenced. This is used to
>   // check if the reference is is invalid.
> ```

nit: "is is"
___
*[src/parser.cc, line 855 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgvcmPDmduxQlBUEeB:-MKgvcmQ6qPFVEphxA_i:b-9ds2ew) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/src/parser.cc#L855)):*
> ```cpp
>       "canonical_link",
>       // //sensor/imu/orientation_reference_frame/custom_rpy/[@parent_frame]
>       "parent_frame",
> ```

nit: definitely feel free to ignore this, but I think it wouldn't be too hard to check the name of the parent element as well as the name of the attribute. I don't think it's worth the extra complexity though
___
*[test/sdf/world_valid_root_reference.sdf, line 13 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgpH9r2fQN43uAwsFY:-MKgpH9r2fQN43uAwsFZ:b5wuhjn) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/test/sdf/world_valid_root_reference.sdf#L13)):*
> ```
>     </model>
>     <frame name="frame1" custom_ns:attr1="__root__"/> <!-- VALID __root__ is being used in a custom attribute -->
>     <custom_ns:elem1 name="__root__" /> <!-- VALID __root__ is being used in a custom element -->
> ```

should we explicitly state that the [reserved names](http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal&cat=pose_semantics_docs&#3-3-reserved-names) rules from SDFormat 1.7 don't apply to custom elements?


<!-- Sent from Reviewable.io -->

2020-10-28 02:12 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 12 of 65 files reviewed, 10 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/SemanticPose.hh, line 99 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgx2mIABeq9HwACohM:-MKgx2mIABeq9HwACohN:b6milpy) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/include/sdf/SemanticPose.hh#L99)):*
> ```Hack
>     /// \param[in] _defaultResolveTo Default frame to resolve-to in Resolve()
>     /// if no frame is specified.
>     /// \param[in] _graph Weak pointer to PoseRelativeToGraph.
> ```

nit: this is a scoped graph now, not a weak pointer


<!-- Sent from Reviewable.io -->

2020-10-28 15:38 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 12 of 65 files reviewed, 7 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/SemanticPose.hh, line 99 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgx2mIABeq9HwACohM:-MKjqaOmCuvpC-Z1gD4g:b82sszy) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/include/sdf/SemanticPose.hh#L99)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: this is a scoped graph now, not a weak pointer
</blockquote></details>

Done in https://github.com/osrf/sdformat/pull/381/commits/f814bb122a347096c8eae900960f891bd973db5f
___
*[src/FrameSemantics.cc, line 224 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhNx6pCGpproW9qEw1:-MKjqcBg6ijsBONQ6NWp:br2w47o) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L224)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Not sure. I think they can be `==0`.
</blockquote></details>

Changes to `==0` in https://github.com/osrf/sdformat/pull/381/commits/f814bb122a347096c8eae900960f891bd973db5f
___
*[src/parser.cc, line 844 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgqCGQ01wZ66mObSq4:-MKjqiO-9arMnrnB94t4:b82sszy) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/src/parser.cc#L844)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: "is is"
</blockquote></details>

Done in https://github.com/osrf/sdformat/pull/381/commits/f814bb122a347096c8eae900960f891bd973db5f
___
*[src/parser.cc, line 855 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgvcmPDmduxQlBUEeB:-MKjqlBj-HNXFFxsDiZ2:bkdo5c0) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/src/parser.cc#L855)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: definitely feel free to ignore this, but I think it wouldn't be too hard to check the name of the parent element as well as the name of the attribute. I don't think it's worth the extra complexity though
</blockquote></details>

Done in https://github.com/osrf/sdformat/pull/381/commits/f814bb122a347096c8eae900960f891bd973db5f. 
___
*[src/ScopedGraph.hh, line 245 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKjZAnFCtqe6FGWTw2s:-MKjZAnGDJtkPHuHRiil:b-5pzk33) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/src/ScopedGraph.hh#L245)):*
> ```Hack
>   /// \brief Weak pointer to either a FrameAttachedToGraph or
>   /// PoseRelativeToGraph.
>   private: std::weak_ptr<T> graphWeak;
> ```

I'm rethinking why this is a `std::weak_ptr`. Since the intention is for the graph to be shared by many ScopedGraph objects, wouldn't it make more sense if it was actually a `std::shared_ptr`?
___
*[test/sdf/world_valid_root_reference.sdf, line 13 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgpH9r2fQN43uAwsFY:-MKjdhDLDK8u4IGUK70v:b-rq3iy0) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/test/sdf/world_valid_root_reference.sdf#L13)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

should we explicitly state that the [reserved names](http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal&cat=pose_semantics_docs&#3-3-reserved-names) rules from SDFormat 1.7 don't apply to custom elements?
</blockquote></details>

I don't see why not. The meaning of the name attribute in a custom element is not defined by the spec, it's defined by the author of the custom namespace, so it would make sense for the rule to not apply here.


<!-- Sent from Reviewable.io -->

2020-10-28 16:07 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 12 of 65 files reviewed, 7 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[src/Model.cc, line 590 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPweX9-grwZPVKxes:-MKjxHox9yDdllfkZHea:b51xvr4) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L590)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is there a way to move these splitting semantics to separate function?

At least for string parsing?

Here's a (crappy) way of how we did this Anzu for model directives (which have now been hoisted to Drake):
https://github.com/RobotLocomotion/drake/blob/cd4890d564d1c44107b2c32b8996346eb2e61a23/multibody/parsing/scoped_names.h#L43-L58
</blockquote></details>

Yes, I think it would be nice to have a data structure for names so that we don't have to do string processing everywhere. I would prefer to do that in a later PR though if it's not a problem?
___
*[src/parser.cc, line 1083 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyBbKf8-V2onmU3a19:-MKjw7DcDxirPRLeqnXo:b3pf3y9) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L1083)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I wonder if we want to revisit this TODO during this development cycle?
</blockquote></details>

I think we would also need to keep the contents of the `<include>` tag to properly address this (i.e for ToString to generate the proper `<include>` string).
I think we can address this when we implement the Interface API. As listed in http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&#1-5-minimal-libsdformat-interface-types-for-non-sdformat-models, `sdf::NestedInclude` will have the URI and the unparsed contents of the `<include>` tag. I don't think it would add too much to also keep track of the parsed contents of `<include>` at that point.


<!-- Sent from Reviewable.io -->

2020-10-28 16:41 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 12 of 65 files reviewed, 5 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[src/parser.cc, line 1083 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJyBbKf8-V2onmU3a19:-MKk-St9Athndvg9AxKQ:bcyvlup) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/parser.cc#L1083)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I think we would also need to keep the contents of the `<include>` tag to properly address this (i.e for ToString to generate the proper `<include>` string).
I think we can address this when we implement the Interface API. As listed in http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&#1-5-minimal-libsdformat-interface-types-for-non-sdformat-models, `sdf::NestedInclude` will have the URI and the unparsed contents of the `<include>` tag. I don't think it would add too much to also keep track of the parsed contents of `<include>` at that point.
</blockquote></details>

OK, sounds good to me
___
*[src/parser.cc, line 855 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgvcmPDmduxQlBUEeB:-MKk1LaxDDROKOnIfDOL:b-rr6dbe) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/src/parser.cc#L855)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done in https://github.com/osrf/sdformat/pull/381/commits/f814bb122a347096c8eae900960f891bd973db5f. 
</blockquote></details>

ok, thanks, I guess it wasn't that hard after all
___
*[src/ScopedGraph.hh, line 245 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKjZAnFCtqe6FGWTw2s:-MKk-e2aD5mhhFZaNs_t:bn8z7gi) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/src/ScopedGraph.hh#L245)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I'm rethinking why this is a `std::weak_ptr`. Since the intention is for the graph to be shared by many ScopedGraph objects, wouldn't it make more sense if it was actually a `std::shared_ptr`?
</blockquote></details>

would this create cycles in the shared pointers that would prevent object destruction? this can be worked around, but it's one of the relevant concerns
___
*[test/sdf/world_valid_root_reference.sdf, line 13 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKgpH9r2fQN43uAwsFY:-MKk4D3f2YavH56oUAXN:bmfsrhh) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/test/sdf/world_valid_root_reference.sdf#L13)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I don't see why not. The meaning of the name attribute in a custom element is not defined by the spec, it's defined by the author of the custom namespace, so it would make sense for the rule to not apply here.
</blockquote></details>

OK, I created an issue to continue this discussion https://github.com/osrf/sdf_tutorials/issues/45


<!-- Sent from Reviewable.io -->

2020-10-28 17:09 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 12 of 65 files reviewed, 5 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[src/ScopedGraph.hh, line 245 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKjZAnFCtqe6FGWTw2s:-MKk9Rvj2rP6WfQo_XVL:bgmxugs) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/src/ScopedGraph.hh#L245)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

would this create cycles in the shared pointers that would prevent object destruction? this can be worked around, but it's one of the relevant concerns
</blockquote></details>

I don't think so. All the pointers would point to one object (PoseRelativeToGraph or FrameAttachedToGraph). There wouldn't be any reference cycles.


<!-- Sent from Reviewable.io -->

2020-10-29 17:58 UTC, EricCousineau-TRI reviewed
Checkpoint - looking great!

> Reviewed 1 of 10 files at r1, 2 of 41 files at r2, 4 of 24 files at r7, 14 of 24 files at r9, 7 of 12 files at r10, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381#-:-MKpVdmj3mWjIuPY8RNt:bhmiv93)* status: 42 of 65 files reviewed, 14 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/Collision.hh, line 145 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpRoO_BkdFOfABCdQc:-MKpRoO_BkdFOfABCdQd:bwfou1i) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/include/sdf/Collision.hh#L145)):*
> ```Hack
>     private: void SetXmlParentName(const std::string &_xmlParentName);
> 
>     /// \brief Give the Scoped PoseRelativeToGraph to be used for resolving
> ```

nit Capitalization of "Scoped" seems odd?
___
*[src/FrameSemantics.cc, line 224 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhNx6pCGpproW9qEw1:-MKpSa7w7qCsbG1cm9oA:b-w196av) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/FrameSemantics.cc#L224)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Changes to `==0` in https://github.com/osrf/sdformat/pull/381/commits/f814bb122a347096c8eae900960f891bd973db5f
</blockquote></details>

OK Thanks!
___
*[src/FrameSemantics.cc, line 218 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpS91j0idMOzqq7UG_:-MKpS91j0idMOzqq7UGa:b-lar0js) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics.cc#L218)):*
> ```cpp
> /// Notation used in this function:
> /// Pf - The placement frame inside the model
> /// R - Relative to frame of the placement frame's pose. This frame is in the
> ```

nit This sentence is an adjective, not a noun... Can you reword it to define a frame, not just describe it?
___
*[src/FrameSemantics.cc, line 238 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpSJtO9_VvZvpS65NI:-MKpSJtO9_VvZvpS65NJ:b391fu9) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics.cc#L238)):*
> ```cpp
> /// When the placement_frame is specified in an SDFormat file, //model/pose
> /// becomes the pose of the placement frame (X_RPf) instead of the pose of the
> /// model frame (X_RM). However, when the model inserted into a pose graph of
> ```

nit "is" missing for "when the model inserted"
___
*[src/FrameSemantics.cc, line 244 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpSTrGDo1JUFPIQJHx:-MKpSTrH3J6GoWRtNZgp:b-q1v1l3) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics.cc#L244)):*
> ```cpp
> //
> /// \param[in] _model Model whose pose to resolve relative to its parent
> /// \param[in] _graph The scoped PoseRelativeTo graph used to resolve the model.
> ```

Whose graph is this? The parent's graph?

(Can you specify that here?)
___
*[src/FrameSemantics_TEST.cc, line 521 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpTBVnBxe4EZEpbRi6:-MKpStw_5zXiXvrYYmdh:b-c927x3) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics_TEST.cc#L521)):*
> ```cpp
>   EXPECT_EQ(1u, modelGraph.Count("M2::L"));
>   EXPECT_EQ(1u, modelGraph.Count("F0"));
>   EXPECT_EQ(0u, modelGraph.Count("invalid"));
> ```

nit Can you also check the global-scoped stuff, like `"world"` or `F1`?
___
*[src/FrameSemantics_TEST.cc, line 542 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpTEsQ0Xq8KJPseACE:-MKpTEsQ0Xq8KJPseACF:b-vj41w8) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics_TEST.cc#L542)):*
> ```cpp
>   EXPECT_TRUE(
>     sdf::resolveFrameAttachedToBody(resolvedBody, modelGraph, "F0").empty());
>   EXPECT_EQ("M2::L", resolvedBody);
> ```

Can you check error behavior for resolving against out-of-scope things, like `F1`?
___
*[src/Model.cc, line 242 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPfI8EZ5pMXN0foA6:-MKpTWLn8giq9thVQUBV:babsbaa) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L242)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Renamed in b1589980. I was actually also thinking about moving all of this graph creation stuff into `sdf::Root`, that way graph creation for both worlds and models will be handled in the same file and there won't be any code needed to figure out if this model is defined in the root or not. Thoughts?
</blockquote></details>

That would be awesome!!! De-duplication (if there aren't a huge number of specialized edge cases) would be ballin'!
___
*[src/Model.cc, line 590 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPweX9-grwZPVKxes:-MKpTitWBiXNrWHvkHaa:bj4smup) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L590)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Yes, I think it would be nice to have a data structure for names so that we don't have to do string processing everywhere. I would prefer to do that in a later PR though if it's not a problem?
</blockquote></details>

Sounds good to me! Can you file a follow-up issue and xref it here? (then I can resolve this discussion)
___
*[src/Model.cc, line 765 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpTsQy3nLecSohlV6K:-MKpTsQy3nLecSohlV6L:bwanls6) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/Model.cc#L765)):*
> ```cpp
>   auto childPoseGraph =
>       this->dataPtr->poseGraph.ChildModelScope(this->Name());
>   for (auto &link : this->dataPtr->links)
> ```

nit Why the ordering of `link, model, joint, frame` in this stanza of for-loops?

Is there a functional or aesthetic reason, or is it kinda arbitrary?
___
*[src/Model_TEST.cc, line 25 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUAUZACw7v487cQeo:-MKpUAUZACw7v487cQep:bga1loh) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/Model_TEST.cc#L25)):*
> ```cpp
> 
> /////////////////////////////////////////////////
> TEST(DOMModel, Construction)
> ```

nit I was confused as to why these were all negative tests until I realized this is empty-construction.

Can you rename this test to reflect that? (if it doesn't hurt regression metrics for y'all's CI?)

If you can't rename it, can you at least specify in a comment here?
___
*[src/parser.cc, line 854 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUTmL7K1JIWhdX0q8:-MKpUTmL7K1JIWhdX0q9:ble3v2v) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/parser.cc#L854)):*
> ```cpp
>       // //model/[@canonical_link]
>       {"model", "canonical_link"},
>       // //sensor/imu/orientation_reference_frame/custom_rpy/[@parent_frame]
> ```

nit Wat? Did we discuss this already?
___
*[src/parser.cc, line 1111 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUkS8-ShWYZk_fn8h:-MKpUkS8-ShWYZk_fn8i:bahzehf) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/parser.cc#L1111)):*
> ```cpp
>         includeSDF->Root()->GetFirstElement()->SetParent(_sdf);
>         _sdf->InsertElement(includeSDF->Root()->GetFirstElement());
>         // TODO: This was used to store the included filename so that when
> ```

nit Is there an issue that should be used to track this?

I have questions, but will defer them to a focused thread.
___
*[src/parser.cc, line 1248 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUupQBe1U84l95gqG:-MKpUupQBe1U84l95gqH:b-td30eb) ([raw file](https://github.com/osrf/sdformat/blob/144f82cf8b994abd2a566a7bbe6ae873a9d92403/src/parser.cc#L1248)):*
> ```cpp
> 
> ///////////// [...]

2020-10-29 18:14 UTC, azeey commented
___
*[src/Model.cc, line 242 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPfI8EZ5pMXN0foA6:-MKpYPKcAocvQo_i3K62:b-4uaw8m) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L242)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

That would be awesome!!! De-duplication (if there aren't a huge number of specialized edge cases) would be ballin'!
</blockquote></details>

OK. Here's a PR: https://github.com/osrf/sdformat/pull/398


<!-- Sent from Reviewable.io -->

2020-10-29 20:26 UTC, EricCousineau-TRI reviewed
> Reviewed 3 of 10 files at r1, 4 of 41 files at r2, 1 of 14 files at r3, 3 of 9 files at r5, 4 of 16 files at r6, 2 of 24 files at r7, 1 of 1 files at r8, 4 of 24 files at r9, 4 of 12 files at r10.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: all files reviewed, 16 unresolved discussions (waiting on @azeey and @scpeters)

___
*[src/ScopedGraph.hh, line 48 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpwuSS-QkHDEENb2N5:-MKpwuSS-QkHDEENb2N6:b-887nbx) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/ScopedGraph.hh#L48)):*
> ```Hack
> 
>   /// \brief The name of this scope. Either world or __model__
>   std::string scopeName {};
> ```

nit It seems like this is more like "scope type name" or "scope context name", e.g. is it for a model, or a world?

Can you update this name  + docstring to better reflect that?
___
*[test/integration/model_dom.cc, line 572 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKq0vXS4zoZjGsL0YZz:-MKq0vXS4zoZjGsL0Y_-:b-ujm3or) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/test/integration/model_dom.cc#L572)):*
> ```cpp
>   // errors[4]
>   // errors[5]
>   // errors[6]
> ```

The `EXPECT_EQ(7u, errors.size())` above indicates that these comments should end after `errors[6]`?
___
*[test/integration/nested_model_with_frames_expected.sdf, line 56 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKq-4EE-VyP8NXXWbnk:-MKq-4EE-VyP8NXXWbnl:bzidah8) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/test/integration/nested_model_with_frames_expected.sdf#L56)):*
> ```
>           <child>L3</child>
>           <axis>
>             <xyz expressed_in='__model__'>0 0 1</xyz>
> ```

nit Can you delete the now-redundant `expressed_in` and `relative_to` attributes? (when they're equal to `__model__`)


<!-- Sent from Reviewable.io -->

2020-10-29 20:26 UTC, EricCousineau-TRI reviewed
Finished!

> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381#-:-MKq1eCZ9xCoCCfOS7Pp:bsewx9m)* status: all files reviewed, 16 unresolved discussions (waiting on @azeey and @scpeters)



<!-- Sent from Reviewable.io -->

2020-10-29 23:40 UTC, scpeters approved these changes
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: all files reviewed, 16 unresolved discussions (waiting on @azeey)

___
*[src/ScopedGraph.hh, line 245 at r10](https://reviewable.io/reviews/osrf/sdformat/381#-MKjZAnFCtqe6FGWTw2s:-MKqijCg5aCgP7y6jt8c:bx2t54i) ([raw file](https://github.com/osrf/sdformat/blob/2a21634532270e9d70007694dacac43d9dd484e4/src/ScopedGraph.hh#L245)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I don't think so. All the pointers would point to one object (PoseRelativeToGraph or FrameAttachedToGraph). There wouldn't be any reference cycles.
</blockquote></details>

ok, as long as none of the graphs have shared pointers to DOM objects, then there shouldn't be any cycles. I think it could be a shared pointer :+1: 


<!-- Sent from Reviewable.io -->

2020-10-29 23:42 UTC, scpeters requested changes
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: all files reviewed, 17 unresolved discussions (waiting on @azeey)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/381#-MKqjJxVBDx7Oy2hgsjy:-MKqjJxVBDx7Oy2hgsjz:bf5xm4) (no related file):*
I didn't mean to approve, I was just trying to publish a comment

---


<!-- Sent from Reviewable.io -->

2020-10-30 05:13 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 49 of 65 files reviewed, 10 unresolved discussions (waiting on @EricCousineau-TRI and @scpeters)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/381#-MKqjJxVBDx7Oy2hgsjy:-MKrQjg-DVCZq0g0CvJ3:bb71kmx) (no related file):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I didn't mean to approve, I was just trying to publish a comment
</blockquote></details>

Okay

---
___
*[include/sdf/Collision.hh, line 145 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpRoO_BkdFOfABCdQc:-MKrtjkC1Tf5ieRZiK5h:bo7v4f5) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/include/sdf/Collision.hh#L145)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Capitalization of "Scoped" seems odd?
</blockquote></details>

Ok, changed to scoped in eef24a0aec049ce4af6670b7cccc08405b81287a
___
*[src/FrameSemantics.cc, line 218 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpS91j0idMOzqq7UG_:-MKrXAEW56UA5HNFAwc1:b-evepdl) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics.cc#L218)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This sentence is an adjective, not a noun... Can you reword it to define a frame, not just describe it?
</blockquote></details>

Would it have helped if I had "Relative-to frame..." instead of "Relative to frame...". How about "The frame relative to which the placement frame's pose is expressed"?
___
*[src/FrameSemantics.cc, line 238 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpSJtO9_VvZvpS65NI:-MKrs2Nn57ay0za89oQd:b-ctu3mp) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics.cc#L238)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "is" missing for "when the model inserted"
</blockquote></details>

Done in 3c61c82c241e7b07cc78f4c2375fac8987697388.
___
*[src/FrameSemantics.cc, line 244 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpSTrGDo1JUFPIQJHx:-MKrsDcr9Nvji6KSelj1:b-ctu3mp) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics.cc#L244)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Whose graph is this? The parent's graph?

(Can you specify that here?)
</blockquote></details>

Done in 3c61c82c241e7b07cc78f4c2375fac8987697388.
___
*[src/FrameSemantics_TEST.cc, line 521 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpTBVnBxe4EZEpbRi6:-MKrsPlO4ASAUEcQEZ4u:b-ctu3mp) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics_TEST.cc#L521)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you also check the global-scoped stuff, like `"world"` or `F1`?
</blockquote></details>

Done in 3c61c82c241e7b07cc78f4c2375fac8987697388.
___
*[src/FrameSemantics_TEST.cc, line 542 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpTEsQ0Xq8KJPseACE:-MKrsOuKEEETrl-x-cgk:b-ctu3mp) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics_TEST.cc#L542)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you check error behavior for resolving against out-of-scope things, like `F1`?
</blockquote></details>

Done in 3c61c82c241e7b07cc78f4c2375fac8987697388.
___
*[src/Model.cc, line 590 at r7](https://reviewable.io/reviews/osrf/sdformat/381#-MJhPweX9-grwZPVKxes:-MKrOmgB5Oe-flVSwAoU:b-feu6eh) ([raw file](https://github.com/osrf/sdformat/blob/6a7482cac600c44ec5a6f28f15c6232aad653ab9/src/Model.cc#L590)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sounds good to me! Can you file a follow-up issue and xref it here? (then I can resolve this discussion)
</blockquote></details>

Ok. I've created an issue https://github.com/osrf/sdformat/issues/400
___
*[src/Model.cc, line 765 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpTsQy3nLecSohlV6K:-MKrP7-r-DjcbWWQFfXY:b-ktrc6u) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/Model.cc#L765)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why the ordering of `link, model, joint, frame` in this stanza of for-loops?

Is there a functional or aesthetic reason, or is it kinda arbitrary?
</blockquote></details>

It's arbitrary. Should I do `model, link, joint, frame`?
___
*[src/Model_TEST.cc, line 25 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUAUZACw7v487cQeo:-MKrapIq7Byzo4oZlzhj:b-3c5q8c) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/Model_TEST.cc#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I was confused as to why these were all negative tests until I realized this is empty-construction.

Can you rename this test to reflect that? (if it doesn't hurt regression metrics for y'all's CI?)

If you can't rename it, can you at least specify in a comment here?
</blockquote></details>

I'd rather just add a comment since the naming pattern is used in all the other DOM objects. 3c61c82c241e7b07cc78f4c2375fac8987697388.
___
*[src/parser.cc, line 854 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUTmL7K1JIWhdX0q8:-MKrbXD7-q7dA11sWywY:b-ekigd8) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/parser.cc#L854)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Wat? Did we discuss this already?
</blockquote></details>

Assuming you're referring to `custom_rpy/[@parent_frame]`, no we didn't, but the spec says it can reference a frame, so I thought I should include it in this list.
___
*[src/parser.cc, line 1111 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUkS8-ShWYZk_fn8h:-MKrSfRo-IXCHj-hi13Z:b-feu6eg) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/parser.cc#L1111)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Is there an issue that should be used to track this?

I have questions, but will defer them to a focused thread.
</blockquote></details>

Ok. I've created an issue https://github.com/osrf/sdformat/issues/401
___
*[src/parser.cc, line 1248 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUupQBe1U84l95gqG:-MKrPzWS8e5VQp2E82zu:b-8fx2u7) ([raw file](https://github.com/osrf/sdformat/blob/144f82cf8b994abd2a566a7bbe6ae873a9d92403/src/parser.cc#L1248)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Ahhhh, soooo much nicer!
</blockquote></details>

:+1: 
___
*[src/parser_TEST.cc, line 114 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUzgc7Y9nMR15XnK7:-MKrT-O10Zu1XUOqagad:b-i0ko7z) ([raw file](https://github.com/osrf/sdformat/blob/144f82cf8b994abd2a566a7bbe6ae873a9d92403/src/parser_TEST.cc#L114)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you explain why this was removed?

Are there tests in this file that should handle nested models? (perhaps for backwards compatibility or something or other?)
</blockquote></details>

These tests all use `sdf::addNestedModel`, which no longer exists. Since the behavior of `<include>` has changed to not use `sdf::addNestedModel`, I don't believe these tests are valid anymore.
___
*[ [...]

2020-10-30 11:06 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - thanks!

> Reviewed 16 of 16 files at r12.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381#-:-MKtAwItDB8-HZ3dwpwY:b-hidk3u)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey)

___
*[src/FrameSemantics.cc, line 218 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpS91j0idMOzqq7UG_:-MKt97L08dsXueYk09iG:bth978l) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics.cc#L218)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Would it have helped if I had "Relative-to frame..." instead of "Relative to frame...". How about "The frame relative to which the placement frame's pose is expressed"?
</blockquote></details>

Ah, gotcha. The latter would have worked, or perhaps even using the identifier as the noun? (or something like that?)

```
R - The `relative_to` frame of the placement frame's //pose element.
```
___
*[src/Model.cc, line 765 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpTsQy3nLecSohlV6K:-MKtA-uX3Z_YM4jktc_o:bd31021) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/Model.cc#L765)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

It's arbitrary. Should I do `model, link, joint, frame`?
</blockquote></details>

Yeah, that may be a bit less "jarring" (in the mildest of sense :P)... But I'm also fine with it staying as-is.

Feel free to dismiss this comment.
___
*[src/Model_TEST.cc, line 25 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUAUZACw7v487cQeo:-MKtAFEqEAH9ksCdNQg7:b-w196av) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/Model_TEST.cc#L25)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I'd rather just add a comment since the naming pattern is used in all the other DOM objects. 3c61c82c241e7b07cc78f4c2375fac8987697388.
</blockquote></details>

OK Thanks!
___
*[src/parser.cc, line 854 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUTmL7K1JIWhdX0q8:-MKtAHCo6Q-tGmQl-4EF:b-d8byzc) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/parser.cc#L854)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Assuming you're referring to `custom_rpy/[@parent_frame]`, no we didn't, but the spec says it can reference a frame, so I thought I should include it in this list.
</blockquote></details>

OK SGTM for now. If you are able, could you include this in the pose frame semantics proposal? (seems like it may need to be incorporated in parsing?)
___
*[src/parser_TEST.cc, line 114 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUzgc7Y9nMR15XnK7:-MKtAb5300xZTAjuCXBE:b56uezr) ([raw file](https://github.com/osrf/sdformat/blob/144f82cf8b994abd2a566a7bbe6ae873a9d92403/src/parser_TEST.cc#L114)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

These tests all use `sdf::addNestedModel`, which no longer exists. Since the behavior of `<include>` has changed to not use `sdf::addNestedModel`, I don't believe these tests are valid anymore.
</blockquote></details>

OK Sounds good!
___
*[test/integration/nested_model_with_frames_expected.sdf, line 56 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKq-4EE-VyP8NXXWbnk:-MKtAlX7Ajw8e3-6m78H:b-jy2dk7) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/test/integration/nested_model_with_frames_expected.sdf#L56)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

The `expressed_in` is actually not redundant since the default would have been the joint frame. The `relative_to` attribute of `L4` is the only one that would be considered redundant, but it is actually set in the source file https://github.com/azeey/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/test/integration/model/test_model_with_frames/model.sdf#L36, so I'm not sure if deleting is the right thing to do. Even if we wanted to delete it, it will actually be a lot more involved since the SDFormat generation deals with `sdf::Element`s and doesn't know that the default value of `//link/pose/[@relative_to]`, which is "", resolves to `__model__`. 
</blockquote></details>

OK Sounds good - thanks for the explanation!

(And d'oh! Thanks for catching my mistake on `expressed_in` :facepalm:)


<!-- Sent from Reviewable.io -->

2020-10-30 14:48 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 63 of 65 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[src/FrameSemantics.cc, line 218 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpS91j0idMOzqq7UG_:-MKtyeKf1KVgBZP9uqFy:b-1s4fdu) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/FrameSemantics.cc#L218)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, gotcha. The latter would have worked, or perhaps even using the identifier as the noun? (or something like that?)

```
R - The `relative_to` frame of the placement frame's //pose element.
```
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/38bee6e780937eff9510573a4b59a8f95175d996
___
*[src/Model.cc, line 765 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpTsQy3nLecSohlV6K:-MKtyh1VE5JqI_wW9Qmw:bftat3k) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/Model.cc#L765)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, that may be a bit less "jarring" (in the mildest of sense :P)... But I'm also fine with it staying as-is.

Feel free to dismiss this comment.
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/38bee6e780937eff9510573a4b59a8f95175d996.
___
*[src/parser.cc, line 854 at r11](https://reviewable.io/reviews/osrf/sdformat/381#-MKpUTmL7K1JIWhdX0q8:-MKty-DbBiCPLExTX8Sl:b9srd7) ([raw file](https://github.com/osrf/sdformat/blob/f4def9cc51d714a44bbf7ca49ff0cb2489fc6e75/src/parser.cc#L854)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK SGTM for now. If you are able, could you include this in the pose frame semantics proposal? (seems like it may need to be incorporated in parsing?)
</blockquote></details>

Ok. Created issues https://github.com/osrf/sdf_tutorials/issues/47 and https://github.com/osrf/sdf_tutorials/issues/48


<!-- Sent from Reviewable.io -->

2020-10-30 21:39 UTC, scpeters requested changes
> Reviewed 1 of 10 files at r1, 4 of 41 files at r2, 1 of 14 files at r3, 3 of 9 files at r5, 3 of 16 files at r6, 11 of 24 files at r7, 1 of 1 files at r8, 7 of 24 files at r9, 8 of 12 files at r10, 2 of 3 files at r11, 13 of 16 files at r12, 4 of 8 files at r14.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 58 of 62 files reviewed, 8 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[src/FrameSemantics.cc, line 311 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvG4oK0IdP1bYqhxZL:-MKvG4oK0IdP1bYqhxZM:b35wou2) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L311)):*
> ```cpp
>   {
>     _out = _out.AddScopeVertex(
>         "", "__root__", scopeContextName, sdf::FrameType::STATIC_MODEL);
> ```

why `STATIC_MODEL`?
___
*[src/FrameSemantics.cc, line 479 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvKFJxBiko1PdSfD7g:-MKvKFJy2AgbvmLi-FdE:b7cru2z) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L479)):*
> ```cpp
>     {
>       // The canonical link is nested, so its vertex should be added
>       // here with an edge from __model__.
> ```

I think this comment can be improved. no vertices are added here, just an edge. also, the canonical link may be nested, but this code also runs for non-nested links
___
*[src/FrameSemantics.cc, line 836 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvLt0b7zV_5TeQdlFz:-MKvLt0c7DS9zjsKfFwJ:b5c5p8x) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L836)):*
> ```cpp
>     auto nestedModelId = outModel.VertexIdByName(nestedModel->Name());
>     // relative_to is empty, so add edge from implicit model frame
>     // to nestedModel
> ```

I would rephrase this: "if relative_to is empty, add edge from implicit model frame to nestedModel"
___
*[src/FrameSemantics.cc, line 968 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvNgXW6e9cthMdDLL8:-MKvNgXX-0zxNhWxDnuY:b-3n8sdi) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L968)):*
> ```cpp
>     auto modelId = _out.VertexIdByName(model->Name());
>     // relative_to is empty, so add edge from implicit model frame
>     // to world
> ```

nit: "if relative_to is empty, add edge from implicit model frame to world"
___
*[src/FrameSemantics.cc, line 1130 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvOuag2bG91QCE2YFx:-MKvOuah7W5QnGX8KT-Y:b-keg86r) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L1130)):*
> ```cpp
>       {
>         std::string graphType =
>             scopeFrameType == sdf::FrameType::WORLD ? "WORLD" : "MODEL";
> ```

nit: add expectation that `FrameType` of `__root__` is either `WORLD` or `MODEL`
___
*[src/FrameSemantics.cc, line 1222 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvPoPbDVDFVcVr9h27:-MKvPoPbDVDFVcVr9h28:b-oqrnyd) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L1222)):*
> ```cpp
>             errors.push_back({ErrorCode::FRAME_ATTACHED_TO_GRAPH_ERROR,
>                 "FrameAttachedToGraph error, "
>                 "LINK/STATIC_MODEL vertex with name [" +
> ```

nit: remove "/STATIC_MODEL"
___
*[src/FrameSemantics.cc, line 1348 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvQXuFC80vlc3WhCrH:-MKvQXuG7HOXcnrT_g2U:b-keg86r) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L1348)):*
> ```cpp
>       {
>         std::string graphType =
>             sourceFrameType == sdf::FrameType::WORLD ? "WORLD" : "MODEL";
> ```

nit: add expectation that `FrameType` of `__root__` is either `WORLD` or `MODEL`
___
*[src/ScopedGraph.hh, line 150 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKv9OOJBwnGXZEQgVn0:-MKv9OOKAtAscsbznf8O:b-git2hj) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/ScopedGraph.hh#L150)):*
> ```Hack
>   /// \brief Adds a scope vertex to the graph. This creates a new
>   /// scope by making a copy of the current scope with a new prefix and scope
>   /// type name. A new scope vertex then added to the graph.
> ```

nit: "vertex then" -> "vertex is then"


<!-- Sent from Reviewable.io -->

2020-10-30 22:26 UTC, scpeters approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 16 files at r12, 4 of 8 files at r14.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381#-:-MKvbfvBDVfJf1gCufr6:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @azeey)

___
*[src/FrameSemantics_TEST.cc, line 64 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvSh9P7RC4KLKv6CE6:-MKvSh9P7RC4KLKv6CE7:b-jr655e) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics_TEST.cc#L64)):*
> ```cpp
>   EXPECT_EQ(8u, graph.Map().size());
>   EXPECT_EQ(8u, graph.Graph().Vertices().size());
>   EXPECT_EQ(6u, graph.Graph().Edges().size());
> ```

Minor non-blocking question: do you know what caused these changes in the count of vertices and edges? is it `__root__` or from the model edge alias?
___
*[test/integration/nested_model.cc, line 328 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvVMKX9YyrM2QiXYX2:-MKvVMKY4dQetN2EIXJ0:bf5sbvu) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/test/integration/nested_model.cc#L328)):*
> ```cpp
>   EXPECT_EQ(3u, model1->LinkCount());
>   EXPECT_EQ(0u, model2->LinkCount());
>   EXPECT_EQ(0u, model3->LinkCount());
> ```

nit: I guess this is because there's no more model flattening? we don't need to add more expectations, but we could consider updating the comment that says "each model has 3 links". or just comment out the expectations instead of modifying them and leave a todo saying to update them to account for non-flattening


<!-- Sent from Reviewable.io -->

2020-11-03 23:28 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 59 of 62 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @scpeters)

___
*[src/FrameSemantics.cc, line 311 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvG4oK0IdP1bYqhxZL:-MLFCeV72A8QK25JVs8j:b-helf4s) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L311)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

why `STATIC_MODEL`?
</blockquote></details>

The `__root__` vertex identifies the scope that contains a root level model. In the PoseRelativeTo graph, this vertex is connected to the model with an edge that holds the value of `//model/pose`. However, in the FrameAttachedTo graph, the vertex is disconnected because nothing is attached to it. Since only links and static models are allowed to be disconnected in this graph, I chose `STATIC_MODEL` as its frame type. I could potentially add a different frame type, but that adds more complexity to the `validateFrameAttachedToGraph` code.
___
*[src/FrameSemantics.cc, line 479 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvKFJxBiko1PdSfD7g:-MLFPh8D3X4JQDGKjAOw:bcdqn08) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L479)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I think this comment can be improved. no vertices are added here, just an edge. also, the canonical link may be nested, but this code also runs for non-nested links
</blockquote></details>

I have updated it in https://github.com/osrf/sdformat/commit/5c42e39b30b4336c47b67ad133523d71f15a2bf9. The comment must have been from an obsolete chunk of code.
___
*[src/FrameSemantics.cc, line 836 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvLt0b7zV_5TeQdlFz:-MLFPuAk-22x6cCUD0hK:b4fv9wm) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L836)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I would rephrase this: "if relative_to is empty, add edge from implicit model frame to nestedModel"
</blockquote></details>

Done. https://github.com/osrf/sdformat/commit/5c42e39b30b4336c47b67ad133523d71f15a2bf9
___
*[src/FrameSemantics.cc, line 968 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvNgXW6e9cthMdDLL8:-MLFPwTTCYnMLGsp_3mb:b-ohqpzl) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L968)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: "if relative_to is empty, add edge from implicit model frame to world"
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/5c42e39b30b4336c47b67ad133523d71f15a2bf9
___
*[src/FrameSemantics.cc, line 1130 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvOuag2bG91QCE2YFx:-MLFPxx813GvjChbWniD:b-yw841o) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L1130)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: add expectation that `FrameType` of `__root__` is either `WORLD` or `MODEL`
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/5c42e39b30b4336c47b67ad133523d71f15a2bf9. I also made the `outDegree != 0` an `else if` branch so it isn't taken if the `scopeFrameType` is not `WORLD` or `STATIC_MODEL`.
___
*[src/FrameSemantics.cc, line 1222 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvPoPbDVDFVcVr9h27:-MLFQQIe6C2F-8kLcNTO:b-ohqpzl) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L1222)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: remove "/STATIC_MODEL"
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/5c42e39b30b4336c47b67ad133523d71f15a2bf9
___
*[src/FrameSemantics.cc, line 1348 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvQXuFC80vlc3WhCrH:-MLFQShkAzqV28YKiGWL:b-yw841o) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L1348)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: add expectation that `FrameType` of `__root__` is either `WORLD` or `MODEL`
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/5c42e39b30b4336c47b67ad133523d71f15a2bf9. I also made the `outDegree != 0` an `else if` branch so it isn't taken if the `scopeFrameType` is not `WORLD` or `STATIC_MODEL`.
___
*[src/FrameSemantics_TEST.cc, line 64 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvSh9P7RC4KLKv6CE6:-MLFMEByChx8SCC9EF96:bmctgxm) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics_TEST.cc#L64)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

Minor non-blocking question: do you know what caused these changes in the count of vertices and edges? is it `__root__` or from the model edge alias?
</blockquote></details>

Yes, the two additional vertices are the `__root__` vertex and the model alias vertex. The one additional edge is the aliasing edge from the model vertex to the corresponding `__model__` vertex. There is no edge from `__root__`, so the count is only increased by 1.
___
*[src/ScopedGraph.hh, line 150 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKv9OOJBwnGXZEQgVn0:-MLFQWFSEgafoqFtPXIr:bm2884f) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/ScopedGraph.hh#L150)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: "vertex then" -> "vertex is then"
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/5c42e39b30b4336c47b67ad133523d71f15a2bf9.
___
*[test/integration/nested_model.cc, line 328 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvVMKX9YyrM2QiXYX2:-MLFQc6b5e64MUE3OBEA:b-w1a800) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/test/integration/nested_model.cc#L328)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: I guess this is because there's no more model flattening? we don't need to add more expectations, but we could consider updating the comment that says "each model has 3 links". or just comment out the expectations instead of modifying them and leave a todo saying to update them to account for non-flattening
</blockquote></details>

Yeah, it's because the included models not flattened anymore. I have commented out the expectations and left a TODO https://github.com/osrf/sdformat/commit/5c42e39b30b4336c47b67ad133523d71f15a2bf9.


<!-- Sent from Reviewable.io -->

2020-11-04 00:55 UTC, EricCousineau-TRI reviewed
> Reviewed 2 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 61 of 62 files reviewed, 5 unresolved discussions (waiting on @azeey and @scpeters)

___
*[include/sdf/Model.hh, line 191 at r16](https://reviewable.io/reviews/osrf/sdformat/381#-MLFjJKP970WCfvqtjnW:-MLFjJKP970WCfvqtjnX:b-ws9ntz) ([raw file](https://github.com/osrf/sdformat/blob/5470e60b22141b2979dd4bcfda0a95b02b249f2c/include/sdf/Model.hh#L191)):*
> ```Hack
>     /// \brief Get the number of explicit frames.
>     /// \return Number of explicit frames contained in this Model object.
>     public: uint64_t FrameCount() const;
> ```

Not sure if this came up on #355:

Methods like `FrameCount()` may now be "asymmetric" w.r.t. `FrameByName()` - i.e. the number of frames reachable by `FrameByName()` exceeds those indicated by `FrameCount()`.

I think that's fine, but we should clarify that in a comment here, saying that it's only the immediate (not nested frames), and make an explicit mention that `FrameByName` can reach more.

(Same for link, joint, and nested models)

Thought about this when seeing the unittest mods about flattened models.
___
*[test/integration/nested_model.cc, line 327 at r16](https://reviewable.io/reviews/osrf/sdformat/381#-MLFijka5XtpVmNvriWu:-MLFijka5XtpVmNvriWv:b8lv5z2) ([raw file](https://github.com/osrf/sdformat/blob/5470e60b22141b2979dd4bcfda0a95b02b249f2c/test/integration/nested_model.cc#L327)):*
> ```cpp
>   // been transformed
>   EXPECT_EQ(3u, model1->LinkCount());
>   // TODO (addisu): Update the following two xpectations to account for the fact
> ```

nit `xpectations` is misspelled


<!-- Sent from Reviewable.io -->

2020-11-04 00:56 UTC, scpeters reviewed
> Reviewed 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey)

___
*[src/FrameSemantics.cc, line 311 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvG4oK0IdP1bYqhxZL:-MLFjG3C4uAFdfotrgSc:b-999226) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L311)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

The `__root__` vertex identifies the scope that contains a root level model. In the PoseRelativeTo graph, this vertex is connected to the model with an edge that holds the value of `//model/pose`. However, in the FrameAttachedTo graph, the vertex is disconnected because nothing is attached to it. Since only links and static models are allowed to be disconnected in this graph, I chose `STATIC_MODEL` as its frame type. I could potentially add a different frame type, but that adds more complexity to the `validateFrameAttachedToGraph` code.
</blockquote></details>

ok, that sounds fine. do you mind adding that justification as a comment in the code?
___
*[src/FrameSemantics.cc, line 1348 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvQXuFC80vlc3WhCrH:-MLFjwgc9YQsuNzqpqTz:bk2xrue) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L1348)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done in https://github.com/osrf/sdformat/commit/5c42e39b30b4336c47b67ad133523d71f15a2bf9. I also made the `outDegree != 0` an `else if` branch so it isn't taken if the `scopeFrameType` is not `WORLD` or `STATIC_MODEL`.
</blockquote></details>

I see that you made this change in `validateFrameAttachedToGraph`, but I don't see the change here in `validatePoseRelativeToGraph`


<!-- Sent from Reviewable.io -->

2020-11-05 14:41 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 60 of 64 files reviewed, 1 unresolved discussion (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/Model.hh, line 191 at r16](https://reviewable.io/reviews/osrf/sdformat/381#-MLFjJKP970WCfvqtjnW:-MLNofMs28y3YtvIHL4N:b-d4aekb) ([raw file](https://github.com/osrf/sdformat/blob/5470e60b22141b2979dd4bcfda0a95b02b249f2c/include/sdf/Model.hh#L191)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Not sure if this came up on #355:

Methods like `FrameCount()` may now be "asymmetric" w.r.t. `FrameByName()` - i.e. the number of frames reachable by `FrameByName()` exceeds those indicated by `FrameCount()`.

I think that's fine, but we should clarify that in a comment here, saying that it's only the immediate (not nested frames), and make an explicit mention that `FrameByName` can reach more.

(Same for link, joint, and nested models)

Thought about this when seeing the unittest mods about flattened models.
</blockquote></details>

Done. Added clarifying comments in f544805d57ea8246a1ffdc8aec69b9b0897f4081.
___
*[src/FrameSemantics.cc, line 311 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvG4oK0IdP1bYqhxZL:-MLNopYKBxf-2qE_cra1:b-kq7uq6) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L311)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

ok, that sounds fine. do you mind adding that justification as a comment in the code?
</blockquote></details>

Done in 661a502687980b6692d7ad568e9706b27544fa4e.
___
*[src/FrameSemantics.cc, line 1348 at r14](https://reviewable.io/reviews/osrf/sdformat/381#-MKvQXuFC80vlc3WhCrH:-MLNoRWm8397vpnOOmtJ:b-7ft9va) ([raw file](https://github.com/osrf/sdformat/blob/b0d3185c5ab139bed15604150d1ed77b884a4128/src/FrameSemantics.cc#L1348)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I see that you made this change in `validateFrameAttachedToGraph`, but I don't see the change here in `validatePoseRelativeToGraph`
</blockquote></details>

Ah, I missed that one. Done in 661a502687980b6692d7ad568e9706b27544fa4e.
___
*[test/integration/nested_model.cc, line 327 at r16](https://reviewable.io/reviews/osrf/sdformat/381#-MLFijka5XtpVmNvriWu:-MLNqRdk93WAz7c40Wyq:b-171u9q) ([raw file](https://github.com/osrf/sdformat/blob/5470e60b22141b2979dd4bcfda0a95b02b249f2c/test/integration/nested_model.cc#L327)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `xpectations` is misspelled
</blockquote></details>

Done in d06275b49051d4c56ad20dd5fe7da713b49e0294.


<!-- Sent from Reviewable.io -->

2020-11-05 18:58 UTC, scpeters requested changes
> Reviewed 4 of 4 files at r17, 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[include/sdf/Root.hh, line 113 at r17](https://reviewable.io/reviews/osrf/sdformat/381#-MLOkjjkDusol7El0kh2:-MLOkjjkDusol7El0kh3:b-sw8jiw) ([raw file](https://github.com/osrf/sdformat/blob/661a502687980b6692d7ad568e9706b27544fa4e/include/sdf/Root.hh#L113)):*
> ```Hack
>     /// of this Root object.
>     /// \remark ModelNameExists() can find nested models that are not immediate
>     /// children of this Root object.
> ```

`Root::ModelNameExists` doesn't actually find nested models; this was enabled for `Model::ModelNameExists` in #355, but only for the `Model` class methods
___
*[include/sdf/World.hh, line 156 at r17](https://reviewable.io/reviews/osrf/sdformat/381#-MLOl9qWEfzw6x_rIcL9:-MLOl9qX8wqmsd820q15:b-tszok2) ([raw file](https://github.com/osrf/sdformat/blob/661a502687980b6692d7ad568e9706b27544fa4e/include/sdf/World.hh#L156)):*
> ```Hack
>     /// \param[in] _name Name of the model.
>     /// To get a model nested in other models, prefix the model name
>     /// with the sequence of nested model names, delimited by "::".
> ```

`World::ModelByName` doesn't actually find nested models; this was enabled for `Model::ModelByName` in #355, but only for the `Model` class methods


<!-- Sent from Reviewable.io -->

2020-11-05 21:05 UTC, azeey commented
___
*[include/sdf/Root.hh, line 113 at r17](https://reviewable.io/reviews/osrf/sdformat/381#-MLOkjjkDusol7El0kh2:-MLPBvY81PXemTeTw1QW:b59os5n) ([raw file](https://github.com/osrf/sdformat/blob/661a502687980b6692d7ad568e9706b27544fa4e/include/sdf/Root.hh#L113)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

`Root::ModelNameExists` doesn't actually find nested models; this was enabled for `Model::ModelNameExists` in #355, but only for the `Model` class methods
</blockquote></details>

hmm, I  hadn't realized that. Do we want to keep it this way or update `Root::ModelNameExists` and `World::ModelNameExists` to also work for nested models?


<!-- Sent from Reviewable.io -->

2020-11-05 23:23 UTC, scpeters requested changes
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[include/sdf/Root.hh, line 113 at r17](https://reviewable.io/reviews/osrf/sdformat/381#-MLOkjjkDusol7El0kh2:-MLPhYo_93_m0XwCs2c5:b-wa22ug) ([raw file](https://github.com/osrf/sdformat/blob/661a502687980b6692d7ad568e9706b27544fa4e/include/sdf/Root.hh#L113)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

hmm, I  hadn't realized that. Do we want to keep it this way or update `Root::ModelNameExists` and `World::ModelNameExists` to also work for nested models?
</blockquote></details>

changing the `Root` and `World` APIs wasn't necessary to support explicitly nested canonical links, so I didn't address it in #355. I think it would be reasonable to make all the `*ByName` and `*NameExists` APIs work like this, but I'd make an issue for it and not try to include it here


<!-- Sent from Reviewable.io -->

2020-11-06 21:06 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: all files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @scpeters)

___
*[include/sdf/Root.hh, line 113 at r17](https://reviewable.io/reviews/osrf/sdformat/381#-MLOkjjkDusol7El0kh2:-MLUL5qL0MAw2Dg_2oxV:b2n4emv) ([raw file](https://github.com/osrf/sdformat/blob/661a502687980b6692d7ad568e9706b27544fa4e/include/sdf/Root.hh#L113)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

changing the `Root` and `World` APIs wasn't necessary to support explicitly nested canonical links, so I didn't address it in #355. I think it would be reasonable to make all the `*ByName` and `*NameExists` APIs work like this, but I'd make an issue for it and not try to include it here
</blockquote></details>

Okay. Created a ticket: https://github.com/osrf/sdformat/issues/412 and reverted the change in https://github.com/osrf/sdformat/commit/8b0665a7a97f48d322978cad2b37ac360e9e1221.
___
*[include/sdf/World.hh, line 156 at r17](https://reviewable.io/reviews/osrf/sdformat/381#-MLOl9qWEfzw6x_rIcL9:-MLUNORA97GgiL9mPihn:b-t811zu) ([raw file](https://github.com/osrf/sdformat/blob/661a502687980b6692d7ad568e9706b27544fa4e/include/sdf/World.hh#L156)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

`World::ModelByName` doesn't actually find nested models; this was enabled for `Model::ModelByName` in #355, but only for the `Model` class methods
</blockquote></details>

Reverted in https://github.com/osrf/sdformat/commit/8b0665a7a97f48d322978cad2b37ac360e9e1221


<!-- Sent from Reviewable.io -->

2020-11-07 00:59 UTC, scpeters reviewed
> Reviewed 2 of 2 files at r19.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[include/sdf/Root.hh, line 113 at r17](https://reviewable.io/reviews/osrf/sdformat/381#-MLOkjjkDusol7El0kh2:-MLVCOAv7wFBqLedClK1:bb85c9b) ([raw file](https://github.com/osrf/sdformat/blob/661a502687980b6692d7ad568e9706b27544fa4e/include/sdf/Root.hh#L113)):*
> ```
>     /// \brief Get the number of models that are immediate (not nested) children
>     /// of this Root object.
> ```

I think this part of the change was ok, since it clarified that the API refers to not-nested children. The `\remark` was the part that I object to.


<!-- Sent from Reviewable.io -->

2020-11-11 00:51 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 62 of 64 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @scpeters)

___
*[include/sdf/Root.hh, line 113 at r17](https://reviewable.io/reviews/osrf/sdformat/381#-MLOkjjkDusol7El0kh2:-MLomC590zKQzsSC5wRZ:b-qcpju4) ([raw file](https://github.com/osrf/sdformat/blob/661a502687980b6692d7ad568e9706b27544fa4e/include/sdf/Root.hh#L113)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

> ```
>     /// \brief Get the number of models that are immediate (not nested) children
>     /// of this Root object.
> ```

I think this part of the change was ok, since it clarified that the API refers to not-nested children. The `\remark` was the part that I object to.
</blockquote></details>

Okay, kept that part of the change in https://github.com/osrf/sdformat/commit/639063300d776ad1dfed7d4130cd7255a378d4de.


<!-- Sent from Reviewable.io -->

2020-11-11 01:35 UTC, scpeters approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r20.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381#-:-MLowMun0Rk-Rk9RAH4m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2020-11-13 16:22 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azeey)

___
*[include/sdf/Model.hh, line 191 at r16](https://reviewable.io/reviews/osrf/sdformat/381#-MLFjJKP970WCfvqtjnW:-MM1PQUV7P-vMkugGdv7:b-w196av) ([raw file](https://github.com/osrf/sdformat/blob/5470e60b22141b2979dd4bcfda0a95b02b249f2c/include/sdf/Model.hh#L191)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done. Added clarifying comments in f544805d57ea8246a1ffdc8aec69b9b0897f4081.
</blockquote></details>

OK Thanks!


<!-- Sent from Reviewable.io -->

2020-11-13 16:31 UTC, EricCousineau-TRI reviewed
> Reviewed 5 of 8 files at r14, 2 of 4 files at r17, 1 of 1 files at r18, 2 of 2 files at r20.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azeey)

___
*[test/integration/nested_model.cc, line 628 at r20](https://reviewable.io/reviews/osrf/sdformat/381#-MM1Qm5CE6gmiM0cVA-E:-MM1Qm5CE6gmiM0cVA-F:bx34d5s) ([raw file](https://github.com/osrf/sdformat/blob/639063300d776ad1dfed7d4130cd7255a378d4de/test/integration/nested_model.cc#L628)):*
> ```cpp
> {
>   const std::string testFile =
>     sdf::filesystem::append(PROJECT_SOURCE_PATH, "test", "integration",
> ```

BTW Did you have a chance to confirm that loading a flattened out model in SDFormat 1.8 fails?


<!-- Sent from Reviewable.io -->

2020-11-18 21:21 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azeey)

___
*[test/integration/nested_model.cc, line 628 at r20](https://reviewable.io/reviews/osrf/sdformat/381#-MM1Qm5CE6gmiM0cVA-E:-MMSC1tp48WleLTjyfJB:b-ptllxx) ([raw file](https://github.com/osrf/sdformat/blob/639063300d776ad1dfed7d4130cd7255a378d4de/test/integration/nested_model.cc#L628)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Did you have a chance to confirm that loading a flattened out model in SDFormat 1.8 fails?
</blockquote></details>

No I haven't. Just so I understand, it should pass if the file has version=1.7, but fail if 1.8?


<!-- Sent from Reviewable.io -->

2020-11-18 21:28 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 57 of 65 files reviewed, all discussions resolved (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[test/integration/nested_model.cc, line 628 at r20](https://reviewable.io/reviews/osrf/sdformat/381#-MM1Qm5CE6gmiM0cVA-E:-MMSFT364VDagJ-csK8O:b-wsrszw) ([raw file](https://github.com/osrf/sdformat/blob/639063300d776ad1dfed7d4130cd7255a378d4de/test/integration/nested_model.cc#L628)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

No I haven't. Just so I understand, it should pass if the file has version=1.7, but fail if 1.8?
</blockquote></details>

Yup! Feel free to do that as follow-up if you'd like this to merge first!


<!-- Sent from Reviewable.io -->

2020-11-18 21:42 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/381)* status: 57 of 65 files reviewed, all discussions resolved (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[test/integration/nested_model.cc, line 628 at r20](https://reviewable.io/reviews/osrf/sdformat/381#-MM1Qm5CE6gmiM0cVA-E:-MMSI_6U6XdNhQFU42gA:b-13cmkb) ([raw file](https://github.com/osrf/sdformat/blob/639063300d776ad1dfed7d4130cd7255a378d4de/test/integration/nested_model.cc#L628)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yup! Feel free to do that as follow-up if you'd like this to merge first!
</blockquote></details>

Okay, yeah, I'll go ahead and merge the PR and create an issue for this.


<!-- Sent from Reviewable.io -->

2020-11-18 21:53 UTC, azeey commented
___
*[test/integration/nested_model.cc, line 628 at r20](https://reviewable.io/reviews/osrf/sdformat/381#-MM1Qm5CE6gmiM0cVA-E:-MMSLIZZ1wjj1z0OVkYe:b-fwpdu6) ([raw file](https://github.com/osrf/sdformat/blob/639063300d776ad1dfed7d4130cd7255a378d4de/test/integration/nested_model.cc#L628)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Okay, yeah, I'll go ahead and merge the PR and create an issue for this.
</blockquote></details>

https://github.com/osrf/sdformat/issues/420


<!-- Sent from Reviewable.io -->

2020-11-18 21:56 UTC, merged