fix: Use PACKAGE_PREFIX_DIR to ensure relocatable CMake install for conan
osrf/sdformat pull request #419
Opened 2020-11-17 13:43 UTC by Pro

Using CMAKE_INSTALL_PREFIX causes build issues when you relocate the installed CMake package, i.e., as it is done in conan.

CMAKE_INSTALL_PREFIX should not be used in the cmake.in files directly. The `@PACKAGE_INIT@` macro initializes `PACKAGE_PREFIX_DIR` correspondingly.

The pc.in files still use `CMAKE_INSTALL_PREFIX` but quickly googling, I did not find a good solution for that.

See also:
https://github.com/ignitionrobotics/ign-tools/pull/30
https://github.com/ignitionrobotics/ign-cmake/pull/129
https://github.com/osrf/gazebo/issues/2782

cc @stefanbuettner

2020-11-17 14:03 UTC, traversaro commented
> The pc.in files still use CMAKE_INSTALL_PREFIX but quickly googling, I did not find a good solution for that.

If you are interested in fully relocatable .pc files, you can always get the (relocatable) location of the `.pc`  file with the `${pcfiledir}` variable, and then compute the relocatable install prefix knowing the relative installation path of the `.pc` file. See a few links in https://github.com/ros2/ros2/issues/606#issuecomment-617603006 .

2020-11-17 14:46 UTC, Pro commented
Thanks @traversaro, I changed it now to `${pcfiledir}`

2020-11-23 22:03 UTC, scpeters requested changes

2020-11-23 22:03 UTC, scpeters commented on cmake/sdformat_pc.in
> +prefix=${pcfiledir}/../..
as discussed in https://github.com/dartsim/dart/pull/1527#discussion_r525493125, this relative path is incorrect on Ubuntu

2021-01-05 07:59 UTC, scpeters commented on cmake/sdformat_pc.in
> +prefix=${pcfiledir}/../..
based on a tip from @jslee02 in https://github.com/dartsim/dart/pull/1529, I've updated this in 41ac64a6adb2b719f745fffeb0859d92497ffa32 to compute the relative path to the pkgconfig folder in cmake

2021-01-08 23:06 UTC, scpeters approved these changes
I think it looks good now, but maybe someone else wants to take a look since I've pushed to this branch? @j-rivero ?

2021-02-04 18:57 UTC, j-rivero approved these changes

2021-02-04 22:29 UTC, merged