Implement SDFormat 1.8 Interface API
osrf/sdformat pull request #475
Opened 2021-01-22 17:36 UTC by azeey

This implements the SDFormat 1.8 Interface API as proposed in http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&#1-5-minimal-libsdformat-interface-types-for-non-sdformat-models.

2021-01-28 19:45 UTC, EricCousineau-TRI commented
Per f2f, having custom parser resolve its own frames internally it's fine for now for the custom parsing structure (and firewalling can simplify dependencies and encapsulation etc.)....

2021-02-05 07:38 UTC, scpeters commented
some conflicts

2021-02-11 17:30 UTC, EricCousineau-TRI commented
Aye. Will await for the `ParserConfig` stuff to be rebased / merged to do a draft review.

2021-02-25 20:06 UTC, EricCousineau-TRI reviewed
Per f2f, good to start reviewing. Next to come is some polishing for reposturing, etc.

> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475#-:-MUPn-HW7NKrgbdcDMP9:bckuaie)* status: 0 of 39 files reviewed, all discussions resolved (waiting on @azeey)



<!-- Sent from Reviewable.io -->

2021-03-03 19:48 UTC, azeey commented
This is ready for review. /cc @EricCousineau-TRI , @scpeters

2021-03-11 18:48 UTC, EricCousineau-TRI commented
Kicking into Reviewable for a larger PR.

2021-03-11 18:58 UTC, EricCousineau-TRI reviewed
> Reviewed 2 of 41 files at r4, 3 of 11 files at r5, 24 of 27 files at r7.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: 26 of 36 files reviewed, 5 unresolved discussions (waiting on @azeey)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/475#-MVXcTlH2cq6LHxkvk1Z:-MVXcTlH2cq6LHxkvk1_:b-ek5hgu) (no related file):*
Do you happen to have an integration PR with Drake based on this work?

---
___
*[include/sdf/InterfaceElements.hh, line 82 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXbqn5ELpq6B3W3CRu:-MVXbqn603hcB52vM_fm:bjeeb7g) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceElements.hh#L82)):*
> ```Hack
>   /// This is a "virtual" XML element that will contain all custom (*unparsed*)
>   /// elements and attributes within `//include`.
>   sdf::ElementPtr virtualCustomElements;
> ```

nit Dumb Q: Given #509, should this just instead store the full `//include` element? (for better parity?)
___
*[include/sdf/InterfaceElements.hh, line 115 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXc5SjA99CXPuY7-AY:-MVXc5SjA99CXPuY7-AZ:b-w4248u) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceElements.hh#L115)):*
> ```Hack
> /// If an exception is raised by this callback, libsdformat will *not* try to
> /// intercept the exception.
> using CustomModelParser =
> ```

nit Since this is a complicated interface, can you add something like "To see an example implementation, please refer to `SOMETHING_TEST.cc`?
___
*[include/sdf/Model.hh, line 37 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXcepEClJufMb-IPCF:-MVXcepEClJufMb-IPCG:bkv0uam) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/Model.hh#L37)):*
> ```Hack
>   //
> 
>   // Forward declarations.
> ```

BTW... Ew... (but I don't have a constructive suggestion for the two-way refs :sweat_smile:)
___
*[include/sdf/World.hh, line 41 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXcvz2ED77PQjxk-WN:-MVXcvz2ED77PQjxk-WO:bgfqv03) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/World.hh#L41)):*
> ```Hack
>   class Actor;
>   class Frame;
>   class InterfaceModel;
> ```

BTW Based on prior pose frame semantics stuff, it'd be great if there were a more principled way to share code between World and Model...
___
*[src/FrameSemantics.hh, line 116 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXd3OaBDq2kGinxu8T:-MVXd3Ob4uMa_TzKtqvJ:b-cal10x) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/FrameSemantics.hh#L116)):*
> ```Hack
>   /// \param[out] _out Graph object to write.
>   /// \param[in] _model Model from which to build attached_to graph.
>   /// \param[in] _root True if the model is a standalone model, i.e,
> ```

nit My naive reading of `_root` implies an element, not a boolean.

Can you change this (and others) to `_is_root`?
___
*[src/FrameSemantics.cc, line 539 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXdL_c3YA-lkZxviBN:-MVXdL_dAgUUuh7Qiprd:bgd6qp6) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/FrameSemantics.cc#L539)):*
> ```cpp
> 
> /////////////////////////////////////////////////
> Errors buildFrameAttachedToGraph(ScopedGraph<FrameAttachedToGraph> &_out,
> ```

nit Dumb high-level Q:

Does this mean that all relevant posturing is now maintained for both proper elements + interface elements?

Did we already discuss implications of having the interface element "shadows" for proper elements, and then the graph only needs to reflect interface elements?


<!-- Sent from Reviewable.io -->

2021-03-11 18:59 UTC, EricCousineau-TRI reviewed
Checkpoint.

> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475#-:-MVXe-p9BlLwm7i3yQJ7:by96gdd)* status: 26 of 36 files reviewed, 5 unresolved discussions (waiting on @azeey)



<!-- Sent from Reviewable.io -->

2021-03-13 01:45 UTC, scpeters requested changes
> Reviewed 1 of 27 files at r3, 1 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: 26 of 36 files reviewed, 6 unresolved discussions (waiting on @azeey)

___
*[include/sdf/Model.hh, line 43 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVZHsAcE4Jze9rEct0e:-MVZHsAcE4Jze9rEct0f:bvuoqwq) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/Model.hh#L43)):*
> ```Hack
>   class Link;
>   class ParserConfig;
>   class NestedInclude;
> ```

`NestedInclude` is defined as a `struct`. Can you match that in this (and other) forward declarations? There are several windows compiler warnings due to this


<!-- Sent from Reviewable.io -->

2021-03-19 15:24 UTC, EricCousineau-TRI reviewed
> Reviewed 6 of 41 files at r4, 1 of 11 files at r5, 2 of 27 files at r7.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: 35 of 36 files reviewed, 11 unresolved discussions (waiting on @azeey)

___
*[src/Utils.cc, line 80 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA2KY968B3m7ayoV5h:-MWA2KY968B3m7ayoV5i:bre6xkd) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/Utils.cc#L80)):*
> ```cpp
> 
> /////////////////////////////////////////////////
> // cppcheck-suppress unusedFunction
> ```

nit Can you state why this is necessary?

I'd think this is only triggered if it's not part of the header file, and not used w/in this translation unit?
Is it still here b/c there's some awkward declaration somewhere else?
___
*[test/test_config.h.in, line 30 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA2bIzDK2gqCV3SRQn:-MWA2bIzDK2gqCV3SRQo:bu1a17s) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/test_config.h.in#L30)):*
> ```
> #define SDF_TMP_DIR "tmp-sdf/"
> 
> // cppcheck-suppress missingInclude
> ```

nit Can you explain why this is necessary?

e.g. ": This file is generated at build-time, and thus can't be accounted for by our static analysis/lint tools"
___
*[test/integration/interface_api.cc, line 17 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA45LK-BkhUggaVofO:-MWA45LL2dtu1xNBqySi:b-xa1p48) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L17)):*
> ```cpp
>  *
>  */
> ```

Can you add a brief overview to this file? e.g.
```
/// \file
/// Provides a simple usage of the interface API by parsing models described in TOML (https://toml.io/en/).
```
___
*[test/integration/interface_api.cc, line 55 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA3Zw9CuotcbfwwJYD:-MWA3Zw9CuotcbfwwJYE:b-x9w46n) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L55)):*
> ```cpp
> std::string keyType(const std::string &_key)
> {
>   static std::unordered_map<std::string, std::string> keyTypes {
> ```

nit This seems like overkill? A `if/else` seems sufficient?
___
*[test/integration/interface_api.cc, line 55 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA3eh73s_KnV7OZaYr:-MWA3eh73s_KnV7OZaYs:b4iqgbh) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L55)):*
> ```cpp
> std::string keyType(const std::string &_key)
> {
>   static std::unordered_map<std::string, std::string> keyTypes {
> ```

nit Do y'all have anything in your styleguide about destructors and non-POD types (types that aren't trivially destructible)?

Asking b/c for GSG + Drake, we have the following:
https://drake.mit.edu/styleguide/cppguide.html#Static_and_Global_Variables


<!-- Sent from Reviewable.io -->

2021-03-19 16:05 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>!
I'd still like to see a rough prototype in Drake, but we can have this merge first + the prototype stuff land in Drake master before doing that.

> Reviewed 1 of 27 files at r7.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475#-:-MWADq6W65mrcEMQAEEH:bfulbn2)* status: all files reviewed, 26 unresolved discussions (waiting on @azeey)

___
*[src/Utils.cc, line 214 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWADhx9Demo1MAuKdYy:-MWADhx9Demo1MAuKdYz:b-kq2rai) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/Utils.cc#L214)):*
> ```cpp
> 
>     const auto &customParsers =  _config.CustomModelParsers();
>     for (auto parserIt = customParsers.rbegin();
> ```

nit Though obvious, can you restate here that you're iterating backwards, and perhaps quote the proposal?
___
*[test/integration/interface_api.cc, line 39 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA7RQw9TC1eQnzoIxD:-MWA7RQw9TC1eQnzoIxE:bc3vrbp) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L39)):*
> ```cpp
> namespace toml
> {
> std::string appendPrefix(const std::string &_input)
> ```

nit For clarity, maybe worth splitting TOML parsing logic into separate file under same folder?
___
*[test/integration/interface_api.cc, line 55 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA3eh73s_KnV7OZaYr:-MWADEu9AnSCptqqsy1N:b-yh7cgz) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L55)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Do y'all have anything in your styleguide about destructors and non-POD types (types that aren't trivially destructible)?

Asking b/c for GSG + Drake, we have the following:
https://drake.mit.edu/styleguide/cppguide.html#Static_and_Global_Variables
</blockquote></details>

K, yeah, seems so:
- https://ignitionrobotics.org/docs/all/contributing#style-guides
- https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

Maybe not critical for a test file, but still important to uphold? (will leave my Reviewable disposition as "discussing", not "blocking")
___
*[test/integration/interface_api.cc, line 214 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA7FdfCtEicGnmoSPN:-MWA7FdfCtEicGnmoSPO:b3v7ke8) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L214)):*
> ```cpp
> 
>   fs.close();
>   // std::cout << "Parsed toml:" << "\n" << doc << std::endl;
> ```

nit Dead code, should be removed?
___
*[test/integration/interface_api.cc, line 217 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA9hQL4GBq0d7gJ4Qt:-MWA9hQL4GBq0d7gJ4Qu:b966b67) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L217)):*
> ```cpp
>   return doc;
> }
> }
> ```

nit Should end namespace with `//  namespace toml`?
___
*[test/integration/interface_api.cc, line 291 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA9mj88IHhavXBQBd0:-MWA9mj88IHhavXBQBd1:b-z5s92u) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L291)):*
> ```cpp
> class InterfaceAPI : public ::testing::Test
> {
>   // cppcheck-suppress unusedFunction
> ```

BTW Ew on this static check... it's marked as override! How can it know it's unused?!
___
*[test/integration/interface_api.cc, line 309 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWAAUzL0uyg1bxkPIWz:-MWAAUzM2X4p_jcQgrth:bx7abuq) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L309)):*
> ```cpp
> 
> /////////////////////////////////////////////////
> TEST_F(InterfaceAPI, NestedIncludeData)
> ```

Same as below - can you indicate that these files aren't actually parsed?

e.g. `file_wont_be_parsed.nonce_1`, `file_wont_be_parsed.nonce_2`?
___
*[test/integration/interface_api.cc, line 331 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWAA-KA5AgniWJoTrcq:-MWAA-KA5AgniWJoTrcr:b-spm13v) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L331)):*
> ```cpp
> </sdf>)";
> 
>   auto testYamlParser =
> ```

My read on all of this is that YAML/TOML aren't actually parsed; this is just meant to InterfaceAPI contracts and error behavior.
It's confusing in the context of seeing TOML code above, etc.

Can you rename these lambdas to reflect that negative aspect?
Or even better, can you just use a nonce name, like `testCustomNonce1Parser`, and use `.nonce_1` / `.nonce_2` as the suffix?
___
*[test/integration/interface_api.cc, line 334 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA86VJBIlnJVVDhwVf:-MWA86VJBIlnJVVDhwVg:bqovnx1) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L334)):*
> ```cpp
>       [&](const sdf::NestedInclude &_include, sdf::Errors &_errors)
>   {
>     if (_include.uri.find(".yaml") == std::string::npos)
> ```

nit This check isn't that robust. Do y'all have code that's similar to `endswith()` from Python?

A simple version:
```cc
bool EndsWith(const std::string& str, const std::string& suffix) {
  if (suffix.size() > str.size()) {
    return false;
  }
  const int diff = str.size() - suffix.size();
  return std::equal(str.begin() + diff, str.end(), suffix.begin());
}
```

(I think this is important if people refer to this file as an example)
___
*[test/integration/interface_api.cc, line 412 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA8auM3DX-e5guIA2d:-MWA8SEIDya1o2guJyY7:b-gv2zzt) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L412)):*
> ```cpp
> </sdf>)";
> 
>   std::vector<int> calledParsers;
> ```

nit Name doesn't immediately convey intent.

Easy to just add a comment, `// Records the order in which custom parsers are called`
or rename to `customParserIndexCallOrder`?
___
*[test/integration/interface_api.cc, line 430 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWABbM6892N_Vpqayd9:-MWABbM7EJeecYGf9saB:b-ed9qvc) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L430)):*
> ```cpp
>   sdf::Errors errors = root.LoadSdfString(testSdf, this->config);
>   EXPECT_TRUE(errors.empty());
>   ASSERT_EQ(3u, calledParsers.size());
> ```

BTW Confirmed that this matches proposal:
```
/// Custom model parsers are visited in the *reverse* of how they are defined.
/// The latest parser gains precedence.
```
http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&#1-5-minimal-libsdformat-interface-types-for-non-sdformat-models
___
*[test/integration/interface_api.cc, line 431 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWABEfz7xZRs5rupEC2:-MWABEfz7xZRs5rupEC3:b-4lprff) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L431)):*
> ```cpp
>   EXPECT_TRUE(errors.empty());
>   ASSERT_EQ(3u, calledParsers.size());
>   EXPECT_EQ(2, calledParsers[0]);
> ```

nit Can you explicitly comment that this is resolving in reverse order?
That, or simply do container comparison? e.g.

```
const std::vector<int> customParserCallOrderExpected{{2, 1, 0}};  // reverse
EXPECT_EQ(customParserCallOrderExpected, customParserCallOrder);
```

I briefly got lost by indexing :grimacing: 
___
*[test/integration/interface_api.cc, line 433 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA8rXU5EUF [...]

2021-03-25 00:02 UTC, jennuine reviewed
Nice work Addisu! I left some minor comments

2021-03-25 00:10 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: 18 of 37 files reviewed, 12 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[include/sdf/InterfaceElements.hh, line 82 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXbqn5ELpq6B3W3CRu:-MWQx0oL5H5HIxGuL7nW:bsxvfxe) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceElements.hh#L82)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Dumb Q: Given #509, should this just instead store the full `//include` element? (for better parity?)
</blockquote></details>

Working: Good point!
___
*[include/sdf/InterfaceElements.hh, line 115 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXc5SjA99CXPuY7-AY:-MWadM8hCgIg2HDk6zlF:b-6blpgv) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceElements.hh#L115)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Since this is a complicated interface, can you add something like "To see an example implementation, please refer to `SOMETHING_TEST.cc`?
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/d773f7072588ba2b63ad0615b129df89d98b143f
___
*[include/sdf/Model.hh, line 43 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVZHsAcE4Jze9rEct0e:-MWadOwECbp7caSJZyIZ:b-6blpgv) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/Model.hh#L43)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

`NestedInclude` is defined as a `struct`. Can you match that in this (and other) forward declarations? There are several windows compiler warnings due to this
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/d773f7072588ba2b63ad0615b129df89d98b143f
___
*[include/sdf/World.hh, line 41 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXcvz2ED77PQjxk-WN:-MWadZrKBuXCiRpNZN6S:brjabqy) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/World.hh#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Based on prior pose frame semantics stuff, it'd be great if there were a more principled way to share code between World and Model...
</blockquote></details>

Yeah, that would be nice. There's a lot of duplication in FrameSemantics.cc too, but the refactoring wouldn't be trivial.
___
*[src/FrameSemantics.hh, line 116 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXd3OaBDq2kGinxu8T:-MWae07W3BAUHQQVhHhk:b-6blpgv) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/FrameSemantics.hh#L116)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit My naive reading of `_root` implies an element, not a boolean.

Can you change this (and others) to `_is_root`?
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/d773f7072588ba2b63ad0615b129df89d98b143f
___
*[src/Utils.cc, line 80 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA2KY968B3m7ayoV5h:-MWaMqAZ5y1eWZc61eDf:b-kf5h2w) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/Utils.cc#L80)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you state why this is necessary?

I'd think this is only triggered if it's not part of the header file, and not used w/in this translation unit?
Is it still here b/c there's some awkward declaration somewhere else?
</blockquote></details>

I don't know why cppcheck issues the warning. The function is declared in `Utils.hh`. This happens on CI too, so it's not just on my system (https://github.com/osrf/sdformat/runs/2188294409#step:4:2013)
___
*[src/Utils.cc, line 214 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWADhx9Demo1MAuKdYy:-MWaeql65Tmq0HIYYM_g:b-6blpgv) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/Utils.cc#L214)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Though obvious, can you restate here that you're iterating backwards, and perhaps quote the proposal?
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/d773f7072588ba2b63ad0615b129df89d98b143f
___
*[test/test_config.h.in, line 30 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA2bIzDK2gqCV3SRQn:-MWaSTGj2jXQcKJGHprm:b-e3rmd9) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/test_config.h.in#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you explain why this is necessary?

e.g. ": This file is generated at build-time, and thus can't be accounted for by our static analysis/lint tools"
</blockquote></details>

This one I was actually able to fix. The test directory needed to be passed to `cppcheck`. Fixed in https://github.com/osrf/sdformat/commit/62e6078ebbe4fff3a1706968491a280c3e06b76a
___
*[test/integration/interface_api.cc, line 55 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA3Zw9CuotcbfwwJYD:-MWaf9O58hvn9KUQi5Pq:bapcu1q) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L55)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This seems like overkill? A `if/else` seems sufficient?
</blockquote></details>

Changed to `if/else` in https://github.com/osrf/sdformat/commit/a6a975f41c9fcb687d119eefedc553cbd2b2c62c. I had envisioned there would be more types to check when I first wrote this function, but that didn't turn out to be the case.
___
*[test/integration/interface_api.cc, line 55 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA3eh73s_KnV7OZaYr:-MWafQRr28wzbsXNhv9I:bt8cqnh) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L55)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

K, yeah, seems so:
- https://ignitionrobotics.org/docs/all/contributing#style-guides
- https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

Maybe not critical for a test file, but still important to uphold? (will leave my Reviewable disposition as "discussing", not "blocking")
</blockquote></details>

Changed to `if/else`.
___
*[test/integration/interface_api.cc, line 214 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA7FdfCtEicGnmoSPN:-MWafTxo0lbP7H_hn-U5:biojdqb) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L214)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Dead code, should be removed?
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/a6a975f41c9fcb687d119eefedc553cbd2b2c62c
___
*[test/integration/interface_api.cc, line 217 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA9hQL4GBq0d7gJ4Qt:-MWafWka9dGZZafEY1x-:biojdqb) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L217)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should end namespace with `//  namespace toml`?
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/a6a975f41c9fcb687d119eefedc553cbd2b2c62c
___
*[test/integration/interface_api.cc, line 291 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA [...]

2021-03-25 01:02 UTC, scpeters reviewed
> Reviewed 2 of 41 files at r4, 2 of 27 files at r7, 6 of 19 files at r8.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: 24 of 37 files reviewed, 21 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @jennuine)

___
*[include/sdf/InterfaceJoint.hh, line 40 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KA_Ml7w3E1kCP9n-r7-40:-MWat84l3Qm1WWn5ye90:biym6jc) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceJoint.hh#L40)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

Does this need to include `_parentName` as a parameter and associated getter?
</blockquote></details>

good question. I don't think so, because joint frames are always attached to the child link:

* http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&#implicit-and-explicit-frames
___
*[include/sdf/World.hh, line 46 at r8](https://reviewable.io/reviews/osrf/sdformat/475#-MWapZ6_8S9AkuvbY96h:-MWapZ6_8S9AkuvbY96i:bpgpiy3) ([raw file](https://github.com/osrf/sdformat/blob/a6a975f41c9fcb687d119eefedc553cbd2b2c62c/include/sdf/World.hh#L46)):*
> ```Hack
>   class ParserConfig;
>   class Physics;
>   class NestedInclude;
> ```

nit: `struct` to fix some windows warnings


<!-- Sent from Reviewable.io -->

2021-03-25 01:22 UTC, scpeters requested changes
> Reviewed 1 of 11 files at r5, 8 of 27 files at r7, 8 of 19 files at r8.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: 32 of 37 files reviewed, 22 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @jennuine)

___
*[include/sdf/InterfaceElements.hh, line 41 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KA_Ml7w3E1kCP9l-r7-41:-MWav98e7lQLe09G_OIQ:b32v57) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceElements.hh#L41)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

```suggestion
  /// not end with a file extension (it will not end with an extension if it refers
```
</blockquote></details>

+1
___
*[include/sdf/InterfaceElements.hh, line 59 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KA_Ml7w3E1kCP9l-r7-59:-MWavXny9IxN9G6iw2Yz:b58mrff) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceElements.hh#L59)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

Should this be `//include/name` (removing `@`) since it is an element not an attribute? Also, should we specify what `localModelName` would be if `//include/name` is not set?
</blockquote></details>

+1 to removing `@`

it currently says `This is nullopt if `//include/name` is not set.` I believe the name is then inferred from the URI in some way?
___
*[include/sdf/InterfaceElements.hh, line 73 at r8](https://reviewable.io/reviews/osrf/sdformat/475#-MWaw8qL67XWbByPOZ2n:-MWaw8qL67XWbByPOZ2o:b-te93xv) ([raw file](https://github.com/osrf/sdformat/blob/a6a975f41c9fcb687d119eefedc553cbd2b2c62c/include/sdf/InterfaceElements.hh#L73)):*
> ```Hack
>   /// \brief The relative-to frame of the pose as specified in
>   /// `//include/pose/@relative_to`. This is nullopt if
>   /// `//include/pose/@relative_to` is set.
> ```

is *not* set?


<!-- Sent from Reviewable.io -->

2021-03-25 01:25 UTC, scpeters requested changes
> Reviewed 1 of 19 files at r8.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: 33 of 37 files reviewed, 23 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @jennuine)

___
*[src/Utils.cc, line 223 at r8](https://reviewable.io/reviews/osrf/sdformat/475#-MWaysBiCX1jKtFsvZvH:-MWaysBjAgbCNF88te5r:bxlt3r7) ([raw file](https://github.com/osrf/sdformat/blob/a6a975f41c9fcb687d119eefedc553cbd2b2c62c/src/Utils.cc#L223)):*
> ```cpp
>       auto poseElem = includeElem->GetElement("pose");
>       include.includeRawPose = poseElem->Get<ignition::math::Pose3d>();
>       include.includePoseRelativeTo = poseElem->Get<std::string>("relative_to");
> ```

not sure if you should check `HasAttribute("relative_to")` here


<!-- Sent from Reviewable.io -->

2021-03-25 03:15 UTC, azeey commented on include/sdf/InterfaceElements.hh
> +  /// not end with a file extension (it will not end an extension if it refers
Done in https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799

2021-03-25 03:17 UTC, azeey commented on include/sdf/InterfaceElements.hh
> +  /// `//include/@name`.
Yeah. Changed in https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799. Also added a comment about what happens if `localModelName` is nullopt. Not sure if you saw @scpeters's comment in reviewable https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KA_Ml7w3E1kCP9l-r7-59

2021-03-25 03:18 UTC, azeey commented on include/sdf/Model.hh
> +    public: Errors Load(sdf::ElementPtr _sdf, const ParserConfig &_config);
Added in https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799

2021-03-25 03:19 UTC, azeey commented on include/sdf/ParserConfig.hh
> +  /// \param[in] _modelParser Callback as described above.
Done in https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799

2021-03-25 03:19 UTC, azeey commented on src/FrameSemantics.cc
> +    outModel.AddVertex(joint.Name(), sdf::FrameType::JOINT).Id();
It used to be assigned to something. Not needed anymore. https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799

2021-03-25 03:19 UTC, azeey commented on src/FrameSemantics.cc
> +    outModel.AddVertex(frame.Name(), sdf::FrameType::FRAME).Id();
https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799

2021-03-25 03:19 UTC, azeey commented on src/FrameSemantics.cc
> +    outModel.AddVertex(joint.Name(), sdf::FrameType::JOINT).Id();
https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799

2021-03-25 03:22 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: 28 of 38 files reviewed, 20 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, @jennuine, and @scpeters)

___
*[include/sdf/InterfaceElements.hh, line 73 at r8](https://reviewable.io/reviews/osrf/sdformat/475#-MWaw8qL67XWbByPOZ2n:-MWbOOhE8YF24QGdWSkW:bf36h36) ([raw file](https://github.com/osrf/sdformat/blob/a6a975f41c9fcb687d119eefedc553cbd2b2c62c/include/sdf/InterfaceElements.hh#L73)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

is *not* set?
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799
___
*[include/sdf/InterfaceJoint.hh, line 40 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KA_Ml7w3E1kCP9n-r7-40:-MWbCwWpCao2VWovScZz:bg25slq) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceJoint.hh#L40)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

good question. I don't think so, because joint frames are always attached to the child link:

* http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&#implicit-and-explicit-frames
</blockquote></details>

Yeah, the only reason we need Joints in the Interface API is to build the frame graphs and the parent link doesn't play a role in that.
___
*[include/sdf/Model.hh, line 305 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KAbfzuwemLFmXer-r7-305:-MWbDcfJByQfpXH3OX66:bj6hxky) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/Model.hh#L305)):*
<details><summary><i>Previously, jennuine (Jenn Nguyen) wrote…</i></summary><blockquote>

Does this TODO need to be addressed for this PR?
</blockquote></details>

I don't know how to address this right now, so I'm thinking of punting. The problem is, if the canonical link is an interface link, as opposed to a regular link, there is no way for this function to return the interface link. I suppose the return type can be `std::pair<std::variant<const Link *, InterfaceLink>, std::string>`, but that feels unwieldy. 
___
*[include/sdf/World.hh, line 46 at r8](https://reviewable.io/reviews/osrf/sdformat/475#-MWapZ6_8S9AkuvbY96h:-MWbOa2w9Eng25Q2TMrb:bf36h36) ([raw file](https://github.com/osrf/sdformat/blob/a6a975f41c9fcb687d119eefedc553cbd2b2c62c/include/sdf/World.hh#L46)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: `struct` to fix some windows warnings
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799
___
*[src/Utils.cc, line 223 at r8](https://reviewable.io/reviews/osrf/sdformat/475#-MWaysBiCX1jKtFsvZvH:-MWbOcPz3lg0HR9RTaI7:b-w7azn5) ([raw file](https://github.com/osrf/sdformat/blob/a6a975f41c9fcb687d119eefedc553cbd2b2c62c/src/Utils.cc#L223)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

not sure if you should check `HasAttribute("relative_to")` here
</blockquote></details>

Added the check in https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799
___
*[test/integration/interface_api.cc, line 17 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA45LK-BkhUggaVofO:-MWbOirmDu6R7UpSYMqz:b-dpp0rv) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you add a brief overview to this file? e.g.
```
/// \file
/// Provides a simple usage of the interface API by parsing models described in TOML (https://toml.io/en/).
```
</blockquote></details>

Done in https://github.com/osrf/sdformat/pull/475/commits/d832ed32c34a3538d0d14817a868350451f473a7
___
*[test/integration/interface_api.cc, line 39 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA7RQw9TC1eQnzoIxD:-MWbOmmXB9KiODRUhXV8:b-dpp0rv) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L39)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For clarity, maybe worth splitting TOML parsing logic into separate file under same folder?
</blockquote></details>

Done in https://github.com/osrf/sdformat/pull/475/commits/d832ed32c34a3538d0d14817a868350451f473a7
___
*[test/integration/interface_api.cc, line 433 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA8rXU5EUFW6tj9qXg:-MWbOrgA5FTqx6qWhKpz:b48ygxl) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L433)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This shows ordering, but doesn't show (a) success or (b) what happens with "conflicting" / "intersecting" parsers (e.g. last one wins)?

Can you capture that here?
</blockquote></details>

Done in https://github.com/osrf/sdformat/pull/475/commits/90cafa20d910201528d0fbc7274db38e014c228f


<!-- Sent from Reviewable.io -->

2021-03-25 03:23 UTC, azeey commented on include/sdf/Model.hh
> +    // TODO (addisu): If the canonical link is inside an interface model, this
I left a comment in reviewable: https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KAbfzuwemLFmXer-r7-305

2021-03-25 03:26 UTC, azeey commented on include/sdf/InterfaceJoint.hh
> +  public: InterfaceJoint(const std::string &_name,
Left a comment in https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KA_Ml7w3E1kCP9n-r7-40
> Yeah, the only reason we need Joints in the Interface API is to build the frame graphs and the parent link doesn't play a role in that.

2021-03-25 03:30 UTC, scpeters requested changes
> Reviewed 3 of 19 files at r8, 8 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: all files reviewed, 19 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @jennuine)

___
*[include/sdf/ParserConfig.hh, line 148 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KA_Ml7w3E1kCP9q-r7-148:-MWbQ5sY544v5OllHNvP:be15rgf) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/ParserConfig.hh#L148)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done in https://github.com/osrf/sdformat/commit/154b8451a731b9a70ad2021a5af558141f8f5799
</blockquote></details>

"as as"
___
*[src/FrameSemantics.cc, line 511 at r8](https://reviewable.io/reviews/osrf/sdformat/475#-MWbO_4F6rE9lJ-J-h66:-MWbO_4F6rE9lJ-J-h67:b1j13q9) ([raw file](https://github.com/osrf/sdformat/blob/a6a975f41c9fcb687d119eefedc553cbd2b2c62c/src/FrameSemantics.cc#L511)):*
> ```cpp
>       else
>       {
>         // Search for the vertex in case the canoncal link is an InterfaceLink
> ```

canoncal -> canonical


<!-- Sent from Reviewable.io -->

2021-03-25 03:36 UTC, azeey reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: 33 of 38 files reviewed, 18 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, @jennuine, and @scpeters)

___
*[include/sdf/InterfaceElements.hh, line 82 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXbqn5ELpq6B3W3CRu:-MWbRriK9IV5v2tSKGUJ:b-as59v9) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceElements.hh#L82)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Working: Good point!
</blockquote></details>

Done in https://github.com/osrf/sdformat/commit/c0af8264f4249a14d8709b11cca15fbf879698b2
___
*[include/sdf/ParserConfig.hh, line 148 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KA_Ml7w3E1kCP9q-r7-148:-MWbRtvz71M8s9_mTGvV:bvhdd3v) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/ParserConfig.hh#L148)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

"as as"
</blockquote></details>

Fixed in https://github.com/osrf/sdformat/pull/475/commits/93f597745ea7c9ebf35cc2c73ed6e9405df875cf
___
*[src/FrameSemantics.cc, line 511 at r8](https://reviewable.io/reviews/osrf/sdformat/475#-MWbO_4F6rE9lJ-J-h66:-MWbS0_w6duq04GfszzN:bowv3gz) ([raw file](https://github.com/osrf/sdformat/blob/a6a975f41c9fcb687d119eefedc553cbd2b2c62c/src/FrameSemantics.cc#L511)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

canoncal -> canonical
</blockquote></details>

Done in https://github.com/osrf/sdformat/pull/475/commits/93f597745ea7c9ebf35cc2c73ed6e9405df875cf


<!-- Sent from Reviewable.io -->

2021-03-25 04:16 UTC, scpeters requested changes
> Reviewed 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: all files reviewed, 18 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @jennuine)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/475#-MWb_jcG3RemeH8G0jLV:-MWb_jcG3RemeH8G0jLW:b-mzlr58) (no related file):*
this all looks good to me; we just need to figure out the windows compiler warnings:

perhaps we can disable C4251 warnings project-wide in this PR with a TODO to revisit with a more proper solution

---


<!-- Sent from Reviewable.io -->

2021-03-25 04:17 UTC, scpeters commented
> this all looks good to me; we just need to figure out the windows compiler warnings:
> 
> perhaps we can disable C4251 warnings project-wide in this PR with a TODO to revisit with a more proper solution

example from ign-rendering:

https://github.com/ignitionrobotics/ign-rendering/blob/ignition-rendering4_4.7.0/ogre2/src/CMakeLists.txt#L5-L12

2021-03-25 04:30 UTC, azeey commented
*[a discussion](https://reviewable.io/reviews/osrf/sdformat/475#-MWb_jcG3RemeH8G0jLV:-MWbd1Ho5r2emGAzzC25:badm28m) (no related file):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

this all looks good to me; we just need to figure out the windows compiler warnings:

perhaps we can disable C4251 warnings project-wide in this PR with a TODO to revisit with a more proper solution
</blockquote></details>

Ignoring C4251 for `NestedInclude` in https://github.com/osrf/sdformat/commit/1676e5d4d6b28dfdce0a727106d9fdbf74f36722  since all the warnings seem to come from there.

---


<!-- Sent from Reviewable.io -->

2021-03-25 04:46 UTC, azeey commented
*[a discussion](https://reviewable.io/reviews/osrf/sdformat/475#-MWb_jcG3RemeH8G0jLV:-MWbhA1iAD4qklKtGjOT:b-z6r603) (no related file):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Ignoring C4251 for `NestedInclude` in https://github.com/osrf/sdformat/commit/1676e5d4d6b28dfdce0a727106d9fdbf74f36722  since all the warnings seem to come from there.
</blockquote></details>

That worked!

---


<!-- Sent from Reviewable.io -->

2021-03-25 04:49 UTC, jennuine approved these changes
LGTM! May want to wait for @scpeters to confirm

2021-03-25 04:49 UTC, scpeters approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475#-:-MWbhh0P1WFLlJaA29Ce:bnfp4nl)* status: all files reviewed, 18 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @jennuine)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/475#-MWb_jcG3RemeH8G0jLV:-MWbhiTW8pjCOCn-z5iU:br4fkav) (no related file):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

That worked!
</blockquote></details>

:confetti_ball: 

---


<!-- Sent from Reviewable.io -->

2021-03-25 05:49 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: all files reviewed, 10 unresolved discussions (waiting on @azeey and @jennuine)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/475#-MVXcTlH2cq6LHxkvk1Z:-MWbvWUu6V-Y5y5YGwc1:bv0kirr) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Do you happen to have an integration PR with Drake based on this work?
</blockquote></details>

OK Dismissing myself here - we can spike test Drake integ after Edifice release!

---
___
*[include/sdf/InterfaceElements.hh, line 82 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXbqn5ELpq6B3W3CRu:-MWbvRPU7lm8o-6WbLtp:b-w196av) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceElements.hh#L82)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done in https://github.com/osrf/sdformat/commit/c0af8264f4249a14d8709b11cca15fbf879698b2
</blockquote></details>

OK Thanks!
___
*[include/sdf/InterfaceElements.hh, line 115 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXc5SjA99CXPuY7-AY:-MWbvOTy-am_jHOFMIXz:bcgzp9s) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/InterfaceElements.hh#L115)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done in https://github.com/osrf/sdformat/commit/d773f7072588ba2b63ad0615b129df89d98b143f
</blockquote></details>

OK Sweet!
___
*[src/FrameSemantics.cc, line 539 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MVXdL_c3YA-lkZxviBN:-MWbvIFx1eDjAZ-ucPRx:bxsezou) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/FrameSemantics.cc#L539)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Dumb high-level Q:

Does this mean that all relevant posturing is now maintained for both proper elements + interface elements?

Did we already discuss implications of having the interface element "shadows" for proper elements, and then the graph only needs to reflect interface elements?
</blockquote></details>

OK Dismissing myself for now.
___
*[src/Utils.cc, line 80 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA2KY968B3m7ayoV5h:-MWbtzhLE3_Th7ZzimWA:b-1fiv9h) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/Utils.cc#L80)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I don't know why cppcheck issues the warning. The function is declared in `Utils.hh`. This happens on CI too, so it's not just on my system (https://github.com/osrf/sdformat/runs/2188294409#step:4:2013)
</blockquote></details>

OK SGTM! (not worth blocking on)
___
*[src/Utils.cc, line 214 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWADhx9Demo1MAuKdYy:-MWbu7TsD4_CbOB4iRvO:b-w196av) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/src/Utils.cc#L214)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done in https://github.com/osrf/sdformat/commit/d773f7072588ba2b63ad0615b129df89d98b143f
</blockquote></details>

OK Thanks!
___
*[test/test_config.h.in, line 30 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA2bIzDK2gqCV3SRQn:-MWbuBVfD_3gMqKMjqyu:bnldu6n) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/test_config.h.in#L30)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

This one I was actually able to fix. The test directory needed to be passed to `cppcheck`. Fixed in https://github.com/osrf/sdformat/commit/62e6078ebbe4fff3a1706968491a280c3e06b76a
</blockquote></details>

OK Yay!
___
*[test/integration/interface_api.cc, line 334 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA86VJBIlnJVVDhwVf:-MWbuMP5DPEg0MatqtX3:b-w196av) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L334)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done in https://github.com/osrf/sdformat/commit/a6a975f41c9fcb687d119eefedc553cbd2b2c62c. Slightly different than yours though using std::string::compare.
</blockquote></details>

OK Thanks!
___
*[test/integration/interface_api.cc, line 431 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWABEfz7xZRs5rupEC2:-MWbuSoCEIvSqzpo5QhL:b-ddsybd) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L431)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done in https://github.com/osrf/sdformat/commit/a6a975f41c9fcb687d119eefedc553cbd2b2c62c
</blockquote></details>

OK Yay! Thanks!
___
*[test/integration/interface_api.cc, line 573 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWA9SRhEtERF4aB2Oe-:-MWbuYy5AoZMOxyRU2Kh:b-w196av) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L573)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

"exp" meant expected. I renamed all of them in https://github.com/osrf/sdformat/commit/a6a975f41c9fcb687d119eefedc553cbd2b2c62c
</blockquote></details>

OK Thanks!
___
*[test/integration/interface_api.cc, line 578 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWABsIOB2VBiR9PQVq8:-MWbu_GC2SgtTjevEKO6:b-3c007a) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L578)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

"dp" -> "doublePendulum" in https://github.com/osrf/sdformat/commit/a6a975f41c9fcb687d119eefedc553cbd2b2c62c
</blockquote></details>

OK Ah, I see - thanks! (a comment to that effect would've also helped - unless I missed it :sweat_smile:)
___
*[test/integration/interface_api.cc, line 709 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MWACksuEiIi7CN5Pnvn:-MWbuo7nA40wtXRT7Z_J:b51vhh2) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/test/integration/interface_api.cc#L709)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

If you meant the file name suffix, I added that in https://github.com/osrf/sdformat/commit/a6a975f41c9fcb687d119eefedc553cbd2b2c62c. The diff can be difficult to parse because I modified the test to check that the reposture callback is called recursively.
</blockquote></details>

OK SGTM! I see the ext check!
___
*[test/integration/toml_parser.hh, line 46 at r11](https://reviewable.io/reviews/osrf/sdformat/475#-MWbv2MRCpfVf7DLBktn:-MWbv2MRCpfVf7DLBkto:b6phrbk) ([raw file](https://github.com/osrf/sdformat/blob/1676e5d4d6b28dfdce0a727106d9fdbf74f36722/test/integration/toml_parser.hh#L46)):*
> ```Hack
> }
> 
> std::string keyType(const std::string &_key)
> ```

BTW Not a huge deal, but this will lead to linker errors if this is included across multiple linked translation units.

Consider using `inline` judiciously, or just put a warning at the top.


<!-- Sent from Reviewable.io -->

2021-03-25 05:50 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: all files reviewed, 10 unresolved discussions (waiting on @azeey and @jennuine)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/475#-MVXcTlH2cq6LHxkvk1Z:-MWbvcwq5sPLR7gWWKer:bzbc5w6) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Dismissing myself here - we can spike test Drake integ after Edifice release!
</blockquote></details>

"spike test" => "review your PR on Drake" :facepalm: 

---


<!-- Sent from Reviewable.io -->

2021-03-25 06:31 UTC, azeey reviewed
> Dismissed @scpeters from a discussion.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: all files reviewed, 9 unresolved discussions (waiting on @jennuine)

*[a discussion](https://reviewable.io/reviews/osrf/sdformat/475#-MVXcTlH2cq6LHxkvk1Z:-MWc3dhmCND08nHxlpG7:bf0nqzk) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

"spike test" => "review your PR on Drake" :facepalm: 
</blockquote></details>

Here's the Drake Prototype. Tests are passing for me locally: https://github.com/RobotLocomotion/drake/compare/master...azeey:sdf_interface_api

---
*[a discussion](https://reviewable.io/reviews/osrf/sdformat/475#-MWb_jcG3RemeH8G0jLV:-MWc440MEZM66A-RkOuc:b-896fix) (no related file):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

:confetti_ball: 
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-03-25 06:37 UTC, azeey reviewed
> Dismissed @jennuine from 8 discussions.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdformat/475)* status: all files reviewed, 8 unresolved discussions (waiting on @jennuine and @scpeters)

___
*[test/integration/toml_parser.hh, line 46 at r11](https://reviewable.io/reviews/osrf/sdformat/475#-MWbv2MRCpfVf7DLBktn:-MWc4yyD8G4sSz2W80vf:bc9b5ab) ([raw file](https://github.com/osrf/sdformat/blob/1676e5d4d6b28dfdce0a727106d9fdbf74f36722/test/integration/toml_parser.hh#L46)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Not a huge deal, but this will lead to linker errors if this is included across multiple linked translation units.

Consider using `inline` judiciously, or just put a warning at the top.
</blockquote></details>

Thanks. Let me do that in a follow up PR.


<!-- Sent from Reviewable.io -->

2021-03-25 06:38 UTC, azeey commented
Since the [Drake prototype](https://github.com/RobotLocomotion/drake/compare/master...azeey:sdf_interface_api) is passing, I'll go ahead and merge this.

2021-03-25 06:57 UTC, merged

2021-03-25 14:36 UTC, EricCousineau-TRI commented
Woot! Awesome!!!

2021-03-25 18:11 UTC, EricCousineau-TRI commented
___
*[include/sdf/Model.hh, line 305 at r7](https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KAbfzuwemLFmXer-r7-305:-MWe_DPD1pLr1kPmL0I3:be3o8th) ([raw file](https://github.com/osrf/sdformat/blob/cbbc0e6fa3341edf77d265d2fee9ca969db2b649/include/sdf/Model.hh#L305)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I left a comment in reviewable: https://reviewable.io/reviews/osrf/sdformat/475#-MUP_KAbfzuwemLFmXer-r7-305
</blockquote></details>

Per VC, Addisu will create an issue.


<!-- Sent from Reviewable.io -->