Clean up use of PROJECT_SOURCE_PATH in tests
osrf/sdformat pull request #549
Opened 2021-04-27 13:06 UTC by mjcarroll

# 🧹 Clean some uses of PROJECT_SOURCE_PATH

This is partially to address compatibility with Bazel builds, but also generally better practice going forward as it handles paths more consistently across operating systems.

Signed-off-by: Michael Carroll <michael@openrobotics.org>

2021-04-27 14:01 UTC, ahcorde requested changes

2021-04-27 14:01 UTC, ahcorde commented on test/integration/nested_model.cc
> +    sdf::testing::TestFile("sdf",
```suggestion
    sdf::testing::TestFile("sdf",
```

2021-04-27 14:01 UTC, ahcorde commented on test/integration/nested_model.cc
> +    sdf::testing::TestFile("sdf",
```suggestion
    sdf::testing::TestFile("sdf",
```

2021-04-27 14:01 UTC, ahcorde commented on test/integration/nested_model.cc
> +      sdf::testing::TestFile("integration",
```suggestion
      sdf::testing::TestFile("integration",
```

2021-04-27 17:35 UTC, azeey commented on tools/code_check.sh
> +  builddir=/home/mjcarroll/workspaces/ign_edifice/build/sdformat11/
This seems unintended.

2021-04-27 18:56 UTC, mjcarroll commented on tools/code_check.sh
> +  builddir=/home/mjcarroll/workspaces/ign_edifice/build/sdformat11/
Yep, thanks

2021-04-28 23:18 UTC, azeey approved these changes
LGTM!

2021-04-30 12:37 UTC, ahcorde approved these changes

2021-04-30 12:42 UTC, merged